#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ملف مدمج - 1 بوت
تم الدمج تلقائياً من جميع ملفات .py
مع Flask - للاستضافات التي تسمح بـ Webserver
"""
import os, sys, threading, time, base64
import types
from flask import Flask, jsonify
from datetime import datetime

# Flask Application
app = Flask(__name__)

# متغير لحفظ حالة البوتات
bots_status = {}
start_time = None

@app.route("/")
def home():
    """الصفحة الرئيسية - تعرض حالة جميع البوتات"""
    global start_time
    uptime = str(datetime.now() - start_time).split(".")[0] if start_time else "0"
    
    html = """
    <!DOCTYPE html>
    <html dir="rtl" lang="ar">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>🤖 نظام إدارة البوتات</title>
        <style>
            * {{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }}
            body {{
                font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
                padding: 20px;
            }}
            .container {{
                background: white;
                border-radius: 20px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                padding: 40px;
                max-width: 600px;
                width: 100%;
            }}
            h1 {{
                color: #667eea;
                text-align: center;
                margin-bottom: 10px;
                font-size: 2em;
            }}
            .uptime {{
                text-align: center;
                color: #666;
                margin-bottom: 30px;
                font-size: 0.9em;
            }}
            .status {{
                background: #f8f9fa;
                border-radius: 15px;
                padding: 25px;
            }}
            .status h2 {{
                color: #10b981;
                text-align: center;
                margin-bottom: 20px;
            }}
            .bot-item {{
                background: white;
                border-radius: 10px;
                padding: 15px;
                margin-bottom: 10px;
                display: flex;
                align-items: center;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }}
            .bot-icon {{
                font-size: 2em;
                margin-left: 15px;
            }}
            .bot-info {{
                flex: 1;
            }}
            .bot-name {{
                font-weight: bold;
                color: #333;
                font-size: 1.1em;
            }}
            .bot-status {{
                color: #10b981;
                font-size: 0.9em;
                margin-top: 5px;
            }}
            .footer {{
                text-align: center;
                margin-top: 30px;
                color: #666;
                font-size: 0.9em;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🤖 نظام إدارة البوتات</h1>
            <div class="uptime">⏱️ وقت التشغيل: {uptime}</div>
            
            <div class="status">
                <h2>✅ جميع البوتات تعمل (1 بوت)</h2>
                <div class="bot-item">
                    <div class="bot-icon">🤖</div>
                    <div class="bot-info">
                        <div class="bot-name">2.py</div>
                        <div class="bot-status">✓ يعمل بشكل طبيعي</div>
                    </div>
                </div>
            </div>
            
            <div class="footer">
                Made with ❤️ | Powered by Flask + Telegram Bot
            </div>
        </div>
    </body>
    </html>
    """
    return html

@app.route("/status")
def status():
    """API endpoint - يعرض حالة البوتات بصيغة JSON"""
    return jsonify({
        "total_bots": 1,
        "status": "running",
        "bots": bots_status,
        "uptime": str(datetime.now() - start_time) if start_time else "0"
    })

@app.route("/health")
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy"}), 200

def run_flask():
    """تشغيل Flask server"""
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)

# أكواد البوتات
BOTS_CODE = {
    1: "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIK8J+OrCDYttin2LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiDYp9mE2KfYrdiq2LHYp9mB2YogLSBVTFRSQSBDT01QUkVTU0lPTgrZiti22LrYtyDYo9mKINmB2YrYr9mK2Ygg2YTYo9mC2LXZiSDYrdivINmF2YXZg9mGIQoK2KfZhNmF2YXZitiy2KfYqjoK4pyFINi22LrYtyDZgtmI2Yog2KzYr9in2YsgLSDZitmC2YTZhCDYp9mE2K3YrNmFINio2YbYs9io2KkgODAtOTUlCuKchSDYs9ix2YrYuSDYrNiv2KfZiyAoM3gg2KPYs9ix2LkpCuKchSDZitiq2LnYp9mF2YQg2YXYuSDYo9mKINit2KzZhSDZgdmK2K/ZitmICuKchSDYsdmB2Lkg2KrZhNmC2KfYptmKINmF2Lkg2KfZhNiq2YLYs9mK2YUg2KXYsNinINmE2LLZhSDYp9mE2KPZhdixCuKchSDYs9is2YTYp9iqINiq2YHYtdmK2YTZitipCgrYp9mE2YXYqti32YTYqNin2Ko6Ci0gUHl0aG9uIDMuOCsKLSBGRm1wZWcgKHN1ZG8gYXB0IGluc3RhbGwgZmZtcGVnKQotIHBpcCBpbnN0YWxsIHB5dGhvbi10ZWxlZ3JhbS1ib3QgcmVxdWVzdHMKCtin2YTYp9iz2KrYrtiv2KfZhToKMS4g2LnYr9mEIEJPVF9UT0tFTiDYo9iv2YbYp9mHCjIuINi02LrZhDogcHl0aG9uMyB2aWRlb19jb21wcmVzc29yX3VsdHJhLnB5CjMuINij2LHYs9mEINix2KfYqNi3INin2YTZgdmK2K/ZitmIINmE2YTYqNmI2KoKIiIiCgppbXBvcnQgb3MKaW1wb3J0IGFzeW5jaW8KaW1wb3J0IHJlcXVlc3RzCmltcG9ydCBzdWJwcm9jZXNzCmltcG9ydCByZQppbXBvcnQgdGltZQppbXBvcnQgbG9nZ2luZwppbXBvcnQganNvbgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKZnJvbSBkYXRldGltZSBpbXBvcnQgZGF0ZXRpbWUKZnJvbSB0ZWxlZ3JhbSBpbXBvcnQgVXBkYXRlLCBJbmxpbmVLZXlib2FyZEJ1dHRvbiwgSW5saW5lS2V5Ym9hcmRNYXJrdXAKZnJvbSB0ZWxlZ3JhbS5leHQgaW1wb3J0IEFwcGxpY2F0aW9uLCBDb21tYW5kSGFuZGxlciwgTWVzc2FnZUhhbmRsZXIsIENhbGxiYWNrUXVlcnlIYW5kbGVyLCBDb250ZXh0VHlwZXMsIGZpbHRlcnMKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojIOKame+4jyDYp9mE2KXYudiv2KfYr9in2KogLSDYudiv2YQg2YfZhtinINmB2YLYtyEKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpCT1RfVE9LRU4gPSAiODUwNDY0ODU1MDpBQUdINFRvNHZSdDczRjBlT0hIQlIzQnNEOUlTYS0wekF0SSIgICMg8J+RiCDYtti5INiq2YjZg9mGINin2YTYqNmI2Kog2YfZhtinClRFTVBfRElSID0gIi4vdGVtcF92aWRlb3MiICAjINmF2KzZhNivINin2YTZhdmE2YHYp9iqINin2YTZhdik2YLYqtipCkxPR1NfRElSID0gIi4vbG9ncyIgICMg2YXYrNmE2K8g2LPYrNmE2KfYqiDYp9mE2KPYrti32KfYoQpNQVhfVEVMRUdSQU1fU0laRV9NQiA9IDUwICAjINit2K8g2LHZgdi5INin2YTZhdmE2YHYp9iqINmB2YogVGVsZWdyYW0gKNmE2YPZhCDYrNiy2KEpCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyDwn5OdINil2LnYr9in2K8g2KfZhNiq2LPYrNmK2YQKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cgpsb2dnaW5nLmJhc2ljQ29uZmlnKAogICAgZm9ybWF0PSclKGFzY3RpbWUpcyAtICUobmFtZSlzIC0gJShsZXZlbG5hbWUpcyAtICUobWVzc2FnZSlzJywKICAgIGxldmVsPWxvZ2dpbmcuSU5GTwopCmxvZ2dlciA9IGxvZ2dpbmcuZ2V0TG9nZ2VyKF9fbmFtZV9fKQoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMg8J+OrCDZhdit2LHZgyDYp9mE2LbYuti3INin2YTZgdin2KbZgiAoVWx0cmEgQ29tcHJlc3NvcikKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpjbGFzcyBVbHRyYUNvbXByZXNzb3I6CiAgICAiIiLZhdit2LHZgyDYtti62Lcg2YHYp9im2YIg2KfZhNmC2YjYqSAtINmK2LbYuti3INij2Yog2YHZitiv2YrZiCDYqNij2YLYtdmJINmC2YjYqSDZhdmF2YPZhtipIiIiCiAgICAKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB0ZW1wX2Rpcj1URU1QX0RJUik6CiAgICAgICAgc2VsZi50ZW1wX2RpciA9IFBhdGgodGVtcF9kaXIpCiAgICAgICAgc2VsZi50ZW1wX2Rpci5ta2RpcihleGlzdF9vaz1UcnVlKQogICAgCiAgICBkZWYgZXh0cmFjdF9nb29nbGVfZHJpdmVfaWQoc2VsZiwgdXJsKToKICAgICAgICAiIiLYp9iz2KrYrtix2KfYrCDZhdi52LHZgSDYp9mE2YXZhNmBINmF2YYg2LHYp9io2LcgR29vZ2xlIERyaXZlIiIiCiAgICAgICAgcGF0dGVybnMgPSBbCiAgICAgICAgICAgIHInaWQ9KFthLXpBLVowLTlfLV0rKScsCiAgICAgICAgICAgIHInL2QvKFthLXpBLVowLTlfLV0rKScsCiAgICAgICAgICAgIHInb3Blblw/aWQ9KFthLXpBLVowLTlfLV0rKScsCiAgICAgICAgXQogICAgICAgIAogICAgICAgIGZvciBwYXR0ZXJuIGluIHBhdHRlcm5zOgogICAgICAgICAgICBtYXRjaCA9IHJlLnNlYXJjaChwYXR0ZXJuLCB1cmwpCiAgICAgICAgICAgIGlmIG1hdGNoOgogICAgICAgICAgICAgICAgcmV0dXJuIG1hdGNoLmdyb3VwKDEpCiAgICAgICAgcmV0dXJuIE5vbmUKICAgIAogICAgZGVmIGRvd25sb2FkX3ZpZGVvKHNlbGYsIHVybCk6CiAgICAgICAgIiIi2KrYrdmF2YrZhCDZgdmK2K/ZitmIINmF2YYg2KPZiiDYsdin2KjYtyIiIgogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+TpSDYqNiv2KEg2KrYrdmF2YrZhCDYp9mE2YHZitiv2YrZiCDZhdmGOiB7dXJsWzoxMDBdfS4uLiIpCiAgICAgICAgCiAgICAgICAgb3V0cHV0X3BhdGggPSBzZWxmLnRlbXBfZGlyIC8gImlucHV0X3ZpZGVvLm1wNCIKICAgICAgICAKICAgICAgICAjINin2YTYqtit2YLZgiDZhdmGIEdvb2dsZSBEcml2ZQogICAgICAgIGZpbGVfaWQgPSBzZWxmLmV4dHJhY3RfZ29vZ2xlX2RyaXZlX2lkKHVybCkKICAgICAgICAKICAgICAgICBpZiBmaWxlX2lkOgogICAgICAgICAgICBsb2dnZXIuaW5mbyhmIvCflI0g2LHYp9io2LcgR29vZ2xlIERyaXZlINiq2YUg2KfZg9iq2LTYp9mB2YciKQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBpbXBvcnQgZ2Rvd24KICAgICAgICAgICAgICAgIGRvd25sb2FkX3VybCA9IGYiaHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL3VjP2lkPXtmaWxlX2lkfSIKICAgICAgICAgICAgICAgIGdkb3duLmRvd25sb2FkKGRvd25sb2FkX3VybCwgc3RyKG91dHB1dF9wYXRoKSwgcXVpZXQ9RmFsc2UpCiAgICAgICAgICAgIGV4Y2VwdCBJbXBvcnRFcnJvcjoKICAgICAgICAgICAgICAgICMg2KfYs9iq2K7Yr9in2YUg2LfYsdmK2YLYqSDYqNiv2YrZhNipCiAgICAgICAgICAgICAgICBkb3dubG9hZF91cmwgPSBmImh0dHBzOi8vZHJpdmUuZ29vZ2xlLmNvbS91Yz9pZD17ZmlsZV9pZH0mZXhwb3J0PWRvd25sb2FkJmNvbmZpcm09dCIKICAgICAgICAgICAgICAgIHJlc3BvbnNlID0gcmVxdWVzdHMuZ2V0KGRvd25sb2FkX3VybCwgc3RyZWFtPVRydWUsIHRpbWVvdXQ9MzAwKQogICAgICAgICAgICAgICAgcmVzcG9uc2UucmFpc2VfZm9yX3N0YXR1cygpCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIHdpdGggb3BlbihvdXRwdXRfcGF0aCwgJ3diJykgYXMgZjoKICAgICAgICAgICAgICAgICAgICBmb3IgY2h1bmsgaW4gcmVzcG9uc2UuaXRlcl9jb250ZW50KGNodW5rX3NpemU9NjU1MzYpOgogICAgICAgICAgICAgICAgICAgICAgICBpZiBjaHVuazoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYud3JpdGUoY2h1bmspCiAgICAgICAgZWxzZToKICAgICAgICAgICAgIyDYqtit2YXZitmEINmF2KjYp9i02LEKICAgICAgICAgICAgbG9nZ2VyLmluZm8oZiLwn5SXINiq2K3ZhdmK2YQg2YXYqNin2LTYsSIpCiAgICAgICAgICAgIHJlc3BvbnNlID0gcmVxdWVzdHMuZ2V0KHVybCwgc3RyZWFtPVRydWUsIHRpbWVvdXQ9MzAwKQogICAgICAgICAgICByZXNwb25zZS5yYWlzZV9mb3Jfc3RhdHVzKCkKICAgICAgICAgICAgCiAgICAgICAgICAgIHdpdGggb3BlbihvdXRwdXRfcGF0aCwgJ3diJykgYXMgZjoKICAgICAgICAgICAgICAgIGZvciBjaHVuayBpbiByZXNwb25zZS5pdGVyX2NvbnRlbnQoY2h1bmtfc2l6ZT02NTUzNik6CiAgICAgICAgICAgICAgICAgICAgaWYgY2h1bms6CiAgICAgICAgICAgICAgICAgICAgICAgIGYud3JpdGUoY2h1bmspCiAgICAgICAgCiAgICAgICAgZmlsZV9zaXplID0gb3MucGF0aC5nZXRzaXplKG91dHB1dF9wYXRoKSAvIDEwMjQgLyAxMDI0CiAgICAgICAgbG9nZ2VyLmluZm8oZiLinIUg2KrZhSDYp9mE2KrYrdmF2YrZhCEg2KfZhNit2KzZhToge2ZpbGVfc2l6ZTouMmZ9INmF2YrYrNin2KjYp9mK2KoiKQogICAgICAgIAogICAgICAgIHJldHVybiBzdHIob3V0cHV0X3BhdGgpCiAgICAKICAgIGRlZiBnZXRfdmlkZW9fZHVyYXRpb24oc2VsZiwgdmlkZW9fcGF0aCk6CiAgICAgICAgIiIi2KfZhNit2LXZiNmEINi52YTZiSDZhdiv2Kkg2KfZhNmB2YrYr9mK2YgiIiIKICAgICAgICBjbWQgPSBbCiAgICAgICAgICAgICdmZnByb2JlJywKICAgICAgICAgICAgJy12JywgJ3F1aWV0JywKICAgICAgICAgICAgJy1wcmludF9mb3JtYXQnLCAnanNvbicsCiAgICAgICAgICAgICctc2hvd19mb3JtYXQnLAogICAgICAgICAgICBzdHIodmlkZW9fcGF0aCkKICAgICAgICBdCiAgICAgICAgCiAgICAgICAgcmVzdWx0ID0gc3VicHJvY2Vzcy5ydW4oY21kLCBjYXB0dXJlX291dHB1dD1UcnVlLCB0ZXh0PVRydWUpCiAgICAgICAgaW5mbyA9IGpzb24ubG9hZHMocmVzdWx0LnN0ZG91dCkKICAgICAgICAKICAgICAgICBkdXJhdGlvbiA9IGZsb2F0KGluZm9bJ2Zvcm1hdCddWydkdXJhdGlvbiddKQogICAgICAgIHJldHVybiBkdXJhdGlvbgogICAgCiAgICBkZWYgdWx0cmFfY29tcHJlc3Moc2VsZiwgaW5wdXRfcGF0aCwgcHJvZ3Jlc3NfY2FsbGJhY2s9Tm9uZSk6CiAgICAgICAgIiIiCiAgICAgICAg2LbYuti3INmB2KfYptmCINin2YTZgtmI2KkhIPCflKUKICAgICAgICAKICAgICAgICDYp9mE2KXYudiv2KfYr9in2Ko6CiAgICAgICAgLSBDUkYgMzggKNij2YLZiNmJINi22LrYtyDZhdi5INis2YjYr9ipINmF2LnZgtmI2YTYqSkKICAgICAgICAtINiv2YLYqSA0ODBwICjZhNiq2YLZhNmK2YQg2KfZhNit2KzZhSDYqNi02YPZhCDZg9io2YrYsSkKICAgICAgICAtIDIwIGZwcyAo2YXYudiv2YQg2KXYt9in2LHYp9iqINmF2YbYrtmB2LYpCiAgICAgICAgLSDYtdmI2KogMzJrIG1vbm8gKNij2YLZhCDYrdis2YUg2YTZhNi12YjYqikKICAgICAgICAtIFByZXNldCB1bHRyYWZhc3QgKNij2LPYsdi5INiz2LHYudipKQogICAgICAgICIiIgogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+UpSDYqNiv2KEg2KfZhNi22LrYtyDYp9mE2YHYp9im2YIg2KfZhNmC2YjYqS4uLiIpCiAgICAgICAgCiAgICAgICAgb3V0cHV0X3BhdGggPSBzZWxmLnRlbXBfZGlyIC8gImNvbXByZXNzZWQubXA0IgogICAgICAgIAogICAgICAgICMg2KfZhNit2LXZiNmEINi52YTZiSDZhdiv2Kkg2KfZhNmB2YrYr9mK2Ygg2YTZhNiq2YLYr9mFCiAgICAgICAgZHVyYXRpb24gPSBzZWxmLmdldF92aWRlb19kdXJhdGlvbihpbnB1dF9wYXRoKQogICAgICAgIGxvZ2dlci5pbmZvKGYi4o+x77iPINmF2K/YqSDYp9mE2YHZitiv2YrZiDoge2R1cmF0aW9uLzYwOi4xZn0g2K/ZgtmK2YLYqSIpCiAgICAgICAgCiAgICAgICAgIyDYo9mF2LEgRkZtcGVnINio2KPZgtmI2Ykg2KXYudiv2KfYr9in2Kog2LbYuti3CiAgICAgICAgY21kID0gWwogICAgICAgICAgICAnZmZtcGVnJywKICAgICAgICAgICAgJy1pJywgc3RyKGlucHV0X3BhdGgpLAogICAgICAgICAgICAjINmB2YrYr9mK2Yg6INi22LrYtyDZgtmI2Yog2KzYr9in2YsKICAgICAgICAgICAgJy1jOnYnLCAnbGlieDI2NCcsICAgICAgICAgICAjINiq2LHZhdmK2LIgSC4yNjQKICAgICAgICAgICAgJy1wcmVzZXQnLCAndWx0cmFmYXN0JywgICAgICAgIyDYo9iz2LHYuSDYs9ix2LnYqQogICAgICAgICAgICAnLWNyZicsICczOCcsICAgICAgICAgICAgICAgICAjINi22LrYtyDZgtmI2Yog2KzYr9in2YsgKDAtNTHYjCA1MSDYo9mC2YjZiSkKICAgICAgICAgICAgJy12ZicsICdzY2FsZT02NDA6LTIsZnBzPTIwJywgIyDYr9mC2KkgNDgwcCArIDIwINil2LfYp9ixL9ir2KfZhtmK2KkKICAgICAgICAgICAgIyDYtdmI2Ko6INi22LrYtyDZgtmI2Yog2KzYr9in2YsKICAgICAgICAgICAgJy1jOmEnLCAnYWFjJywgICAgICAgICAgICAgICAjINiq2LHZhdmK2LIgQUFDCiAgICAgICAgICAgICctYjphJywgJzMyaycsICAgICAgICAgICAgICAgIyDZhdi52K/ZhCDYqNiqINmF2YbYrtmB2LYg2KzYr9in2YsKICAgICAgICAgICAgJy1hYycsICcxJywgICAgICAgICAgICAgICAgICAjINi12YjYqiDYo9it2KfYr9mKIChtb25vKQogICAgICAgICAgICAnLWFyJywgJzIyMDUwJywgICAgICAgICAgICAgICMg2YXYudiv2YQg2LnZitmG2KfYqiDZhdmG2K7Zgdi2CiAgICAgICAgICAgICMg2KrYrdiz2YrZhtin2Kog2KXYttin2YHZitipCiAgICAgICAgICAgICctbW92ZmxhZ3MnLCAnK2Zhc3RzdGFydCcsICAgIyDYqti02LrZitmEINiz2LHZiti5CiAgICAgICAgICAgICctbWF4X211eGluZ19xdWV1ZV9zaXplJywgJzk5OTknLCAgIyDZhNiq2KzZhtioINin2YTYo9iu2LfYp9ihCiAgICAgICAgICAgICcteScsICAgICAgICAgICAgICAgICAgICAgICAgIyDYp9iz2KrYqNiv2KfZhCDYp9mE2YXZhNmBCiAgICAgICAgICAgIHN0cihvdXRwdXRfcGF0aCkKICAgICAgICBdCiAgICAgICAgCiAgICAgICAgbG9nZ2VyLmluZm8oZiLimpnvuI8g2KXYudiv2KfYr9in2Kog2KfZhNi22LrYtzogQ1JGPTM4LCA0ODBwLCAyMGZwcywgQXVkaW89MzJrIG1vbm8iKQogICAgICAgIAogICAgICAgICMg2KrYtNi62YrZhCBGRm1wZWcKICAgICAgICBwcm9jZXNzID0gc3VicHJvY2Vzcy5Qb3BlbigKICAgICAgICAgICAgY21kLAogICAgICAgICAgICBzdGRvdXQ9c3VicHJvY2Vzcy5QSVBFLAogICAgICAgICAgICBzdGRlcnI9c3VicHJvY2Vzcy5QSVBFLAogICAgICAgICAgICB1bml2ZXJzYWxfbmV3bGluZXM9VHJ1ZQogICAgICAgICkKICAgICAgICAKICAgICAgICAjINmF2LHYp9mC2KjYqSDYp9mE2KrZgtiv2YUKICAgICAgICBmb3IgbGluZSBpbiBwcm9jZXNzLnN0ZGVycjoKICAgICAgICAgICAgaWYgJ3RpbWU9JyBpbiBsaW5lOgogICAgICAgICAgICAgICAgbWF0Y2ggPSByZS5zZWFyY2gocid0aW1lPShcZCspOihcZCspOihcZCspJywgbGluZSkKICAgICAgICAgICAgICAgIGlmIG1hdGNoOgogICAgICAgICAgICAgICAgICAgIGgsIG0sIHMgPSBtYXAoaW50LCBtYXRjaC5ncm91cHMoKSkKICAgICAgICAgICAgICAgICAgICBjdXJyZW50X3RpbWUgPSBoICogMzYwMCArIG0gKiA2MCArIHMKICAgICAgICAgICAgICAgICAgICBwcm9ncmVzcyA9IChjdXJyZW50X3RpbWUgLyBkdXJhdGlvbikgKiAxMDAgaWYgZHVyYXRpb24gPiAwIGVsc2UgMAogICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIGlmIHByb2dyZXNzX2NhbGxiYWNrOgogICAgICAgICAgICAgICAgICAgICAgICBwcm9ncmVzc19jYWxsYmFjayhwcm9ncmVzcywgY3VycmVudF90aW1lLCBkdXJhdGlvbikKICAgICAgICAKICAgICAgICBwcm9jZXNzLndhaXQoKQogICAgICAgIAogICAgICAgIGlmIHByb2Nlc3MucmV0dXJuY29kZSAhPSAwOgogICAgICAgICAgICByYWlzZSBFeGNlcHRpb24oZiLZgdi02YQg2KfZhNi22LrYtyEiKQogICAgICAgIAogICAgICAgICMg2K3Ys9in2Kgg2YbYs9io2Kkg2KfZhNi22LrYtwogICAgICAgIG9yaWdpbmFsX3NpemUgPSBvcy5wYXRoLmdldHNpemUoaW5wdXRfcGF0aCkgLyAxMDI0IC8gMTAyNAogICAgICAgIGNvbXByZXNzZWRfc2l6ZSA9IG9zLnBhdGguZ2V0c2l6ZShvdXRwdXRfcGF0aCkgLyAxMDI0IC8gMTAyNAogICAgICAgIGNvbXByZXNzaW9uX3JhdGlvID0gKDEgLSBjb21wcmVzc2VkX3NpemUgLyBvcmlnaW5hbF9zaXplKSAqIDEwMAogICAgICAgIAogICAgICAgIGxvZ2dlci5pbmZvKGYi4pyFINiq2YUg2KfZhNi22LrYtyDYqNmG2KzYp9itISIpCiAgICAgICAgbG9nZ2VyLmluZm8oZiLwn5OKINin2YTYrdis2YUg2KfZhNij2LXZhNmKOiB7b3JpZ2luYWxfc2l6ZTouMmZ9INmF2YrYrNin2KjYp9mK2KoiKQogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+TpiDYp9mE2K3YrNmFINin2YTZhdi22LrZiNi3OiB7Y29tcHJlc3NlZF9zaXplOi4yZn0g2YXZitis2KfYqNin2YrYqiIpCiAgICAgICAgbG9nZ2VyLmluZm8oZiLwn46vINmG2LPYqNipINin2YTYqtmI2YHZitixOiB7Y29tcHJlc3Npb25fcmF0aW86LjFmfSUiKQogICAgICAgIAogICAgICAgIHJldHVybiBzdHIob3V0cHV0X3BhdGgpLCBjb21wcmVzc2VkX3NpemUKICAgIAogICAgZGVmIHNwbGl0X3ZpZGVvX2lmX25lZWRlZChzZWxmLCB2aWRlb19wYXRoLCBtYXhfc2l6ZV9tYj1NQVhfVEVMRUdSQU1fU0laRV9NQik6CiAgICAgICAgIiIi2KrZgtiz2YrZhSDYp9mE2YHZitiv2YrZiCDYpdiw2Kcg2YPYp9mGINij2YPYqNixINmF2YYg2KfZhNit2K8g2KfZhNmF2LPZhdmI2K0iIiIKICAgICAgICBmaWxlX3NpemUgPSBvcy5wYXRoLmdldHNpemUodmlkZW9fcGF0aCkgLyAxMDI0IC8gMTAyNAogICAgICAgIAogICAgICAgIGlmIGZpbGVfc2l6ZSA8PSBtYXhfc2l6ZV9tYjoKICAgICAgICAgICAgbG9nZ2VyLmluZm8oZiLinIUg2KfZhNit2KzZhSDZhdmG2KfYs9ioOiB7ZmlsZV9zaXplOi4yZn0g2YXZitis2KfYqNin2YrYqiIpCiAgICAgICAgICAgIHJldHVybiBbdmlkZW9fcGF0aF0KICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKaoO+4jyDYp9mE2YHZitiv2YrZiCDZg9io2YrYsSAoe2ZpbGVfc2l6ZTouMmZ9IE1CKSAtINiz2YrYqtmFINin2YTYqtmC2LPZitmFLi4uIikKICAgICAgICAKICAgICAgICAjINit2LPYp9ioINi52K/YryDYp9mE2KPYrNiy2KfYoSDYp9mE2YXYt9mE2YjYqNipCiAgICAgICAgbnVtX3BhcnRzID0gaW50KGZpbGVfc2l6ZSAvIG1heF9zaXplX21iKSArIDEKICAgICAgICBkdXJhdGlvbiA9IHNlbGYuZ2V0X3ZpZGVvX2R1cmF0aW9uKHZpZGVvX3BhdGgpCiAgICAgICAgcGFydF9kdXJhdGlvbiA9IGR1cmF0aW9uIC8gbnVtX3BhcnRzCiAgICAgICAgCiAgICAgICAgbG9nZ2VyLmluZm8oZiLinILvuI8g2LPZitiq2YUg2KfZhNiq2YLYs9mK2YUg2KXZhNmJIHtudW1fcGFydHN9INij2KzYstin2KEiKQogICAgICAgIAogICAgICAgIHBhcnRzID0gW10KICAgICAgICAKICAgICAgICBmb3IgaSBpbiByYW5nZShudW1fcGFydHMpOgogICAgICAgICAgICBzdGFydF90aW1lID0gaSAqIHBhcnRfZHVyYXRpb24KICAgICAgICAgICAgcGFydF9wYXRoID0gc2VsZi50ZW1wX2RpciAvIGYicGFydF97aSsxOjAyZH0ubXA0IgogICAgICAgICAgICAKICAgICAgICAgICAgY21kID0gWwogICAgICAgICAgICAgICAgJ2ZmbXBlZycsCiAgICAgICAgICAgICAgICAnLWknLCBzdHIodmlkZW9fcGF0aCksCiAgICAgICAgICAgICAgICAnLXNzJywgc3RyKHN0YXJ0X3RpbWUpLAogICAgICAgICAgICAgICAgJy10Jywgc3RyKHBhcnRfZHVyYXRpb24pLAogICAgICAgICAgICAgICAgJy1jJywgJ2NvcHknLCAgIyDZhtiz2K4g2KjYr9mI2YYg2KXYudin2K/YqSDYqtix2YXZitiyICjYs9ix2YrYuSkKICAgICAgICAgICAgICAgICcteScsCiAgICAgICAgICAgICAgICBzdHIocGFydF9wYXRoKQogICAgICAgICAgICBdCiAgICAgICAgICAgIAogICAgICAgICAgICBsb2dnZXIuaW5mbyhmIuKcgu+4jyDYqtmC2LPZitmFINin2YTYrNiy2KEge2krMX0ve251bV9wYXJ0c30uLi4iKQogICAgICAgICAgICBzdWJwcm9jZXNzLnJ1bihjbWQsIGNhcHR1cmVfb3V0cHV0PVRydWUsIGNoZWNrPVRydWUpCiAgICAgICAgICAgIAogICAgICAgICAgICBwYXJ0cy5hcHBlbmQoc3RyKHBhcnRfcGF0aCkpCiAgICAgICAgCiAgICAgICAgbG9nZ2VyLmluZm8oZiLinIUg2KrZhSDYp9mE2KrZgtiz2YrZhSDYpdmE2Ykge2xlbihwYXJ0cyl9INij2KzYstin2KEiKQogICAgICAgIHJldHVybiBwYXJ0cwoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMg8J+kliDYp9mE2KjZiNiqCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKY2xhc3MgVWx0cmFDb21wcmVzc29yQm90OgogICAgIiIi2KjZiNiqINi22LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiDYp9mE2YHYp9im2YIiIiIKICAgIAogICAgZGVmIF9faW5pdF9fKHNlbGYsIHRva2VuKToKICAgICAgICBzZWxmLnRva2VuID0gdG9rZW4KICAgICAgICBzZWxmLmFwcCA9IEFwcGxpY2F0aW9uLmJ1aWxkZXIoKS50b2tlbih0b2tlbikuYnVpbGQoKQogICAgICAgIHNlbGYuY29tcHJlc3NvciA9IFVsdHJhQ29tcHJlc3NvcigpCiAgICAgICAgCiAgICAgICAgIyDYqtiz2KzZitmEINin2YTZhdi52KfZhNis2KfYqgogICAgICAgIHNlbGYuYXBwLmFkZF9oYW5kbGVyKENvbW1hbmRIYW5kbGVyKCJzdGFydCIsIHNlbGYuc3RhcnRfY29tbWFuZCkpCiAgICAgICAgc2VsZi5hcHAuYWRkX2hhbmRsZXIoQ29tbWFuZEhhbmRsZXIoImhlbHAiLCBzZWxmLmhlbHBfY29tbWFuZCkpCiAgICAgICAgc2VsZi5hcHAuYWRkX2hhbmRsZXIoTWVzc2FnZUhhbmRsZXIoZmlsdGVycy5URVhUICYgfmZpbHRlcnMuQ09NTUFORCwgc2VsZi5oYW5kbGVfdXJsKSkKICAgIAogICAgYXN5bmMgZGVmIHN0YXJ0X2NvbW1hbmQoc2VsZiwgdXBkYXRlOiBVcGRhdGUsIGNvbnRleHQ6IENvbnRleHRUeXBlcy5ERUZBVUxUX1RZUEUpOgogICAgICAgICIiItix2LPYp9mE2Kkg2KfZhNio2K/Yp9mK2KkiIiIKICAgICAgICB3ZWxjb21lX3RleHQgPSAoCiAgICAgICAgICAgICLwn46sICoq2YXYsdit2KjYp9mLINio2YMg2YHZiiDYttin2LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiDYp9mE2YHYp9im2YIhKipcblxuIgogICAgICAgICAgICAi8J+UpSAqKtmK2LbYuti3INij2Yog2YHZitiv2YrZiCDZhNij2YLYtdmJINit2K8g2YXZhdmD2YYhKipcblxuIgogICAgICAgICAgICAi8J+TiyAqKtmD2YrZgSDYqtiz2KrYrtiv2YXZhtmKOioqXG4iCiAgICAgICAgICAgICIx77iP4oOjINij2LHYs9mEINix2KfYqNi3INin2YTZgdmK2K/ZitmIIChHb29nbGUgRHJpdmUg2KPZiCDYsdin2KjYtyDZhdio2KfYtNixKVxuIgogICAgICAgICAgICAiMu+4j+KDoyDYp9mG2KrYuNixINmC2YTZitmE2KfZiy4uLiDij7NcbiIKICAgICAgICAgICAgIjPvuI/ig6Mg2KfYrdi12YQg2LnZhNmJINin2YTZgdmK2K/ZitmIINin2YTZhdi22LrZiNi3ISDinIVcblxuIgogICAgICAgICAgICAi8J+SqiAqKtin2YTZhdmF2YrYstin2Ko6KipcbiIKICAgICAgICAgICAgIuKAoiDYtti62Lcg2YLZiNmKINis2K/Yp9mLICjYqtmI2YHZitixIDgwLTk1JSlcbiIKICAgICAgICAgICAgIuKAoiDYs9ix2YrYuSDYrNiv2KfZi1xuIgogICAgICAgICAgICAi4oCiINmK2KrYudin2YXZhCDZhdi5INij2Yog2K3YrNmFXG4iCiAgICAgICAgICAgICLigKIg2LHZgdi5INiq2YTZgtin2KbZiiDZhdi5INin2YTYqtmC2LPZitmFXG5cbiIKICAgICAgICAgICAgIvCfhpgg2YTZhNmF2LPYp9i52K/YqTogL2hlbHAiCiAgICAgICAgKQogICAgICAgIAogICAgICAgIGF3YWl0IHVwZGF0ZS5tZXNzYWdlLnJlcGx5X3RleHQod2VsY29tZV90ZXh0LCBwYXJzZV9tb2RlPSdNYXJrZG93bicpCiAgICAKICAgIGFzeW5jIGRlZiBoZWxwX2NvbW1hbmQoc2VsZiwgdXBkYXRlOiBVcGRhdGUsIGNvbnRleHQ6IENvbnRleHRUeXBlcy5ERUZBVUxUX1RZUEUpOgogICAgICAgICIiItix2LPYp9mE2Kkg2KfZhNmF2LPYp9i52K/YqSIiIgogICAgICAgIGhlbHBfdGV4dCA9ICgKICAgICAgICAgICAgIvCfk5ogKirYr9mE2YrZhCDYp9mE2KfYs9iq2K7Yr9in2YU6KipcblxuIgogICAgICAgICAgICAiKipHb29nbGUgRHJpdmU6KipcbiIKICAgICAgICAgICAgIuKAoiDYo9ix2LPZhCDYsdin2KjYtyDYp9mE2YXZhNmBINmF2KjYp9i02LHYqVxuIgogICAgICAgICAgICAi4oCiINiq2KPZg9ivINij2YYg2KfZhNmF2YTZgSDYudin2YUgKEFueW9uZSB3aXRoIGxpbmspXG5cbiIKICAgICAgICAgICAgIioq2LHYp9io2Lcg2YXYqNin2LTYsToqKlxuIgogICAgICAgICAgICAi4oCiINij2Yog2LHYp9io2Lcg2YrZhtiq2YfZiiDYqNmAIC5tcDRcblxuIgogICAgICAgICAgICAiKirYpdi52K/Yp9iv2KfYqiDYp9mE2LbYuti3OioqXG4iCiAgICAgICAgICAgICLigKIg2KfZhNiv2YLYqTogNDgwcFxuIgogICAgICAgICAgICAi4oCiINmF2LnYr9mEINin2YTYpdi32KfYsdin2Ko6IDIwIGZwc1xuIgogICAgICAgICAgICAi4oCiINin2YTYtdmI2Ko6IDMyayBtb25vXG4iCiAgICAgICAgICAgICLigKIg2KrZiNmB2YrYsTogODAtOTUlINmF2YYg2KfZhNit2KzZhVxuXG4iCiAgICAgICAgICAgICLwn5KhICoq2YbYtdmK2K3YqToqKiDYp9mE2LbYuti3INin2YTZgtmI2Yog2YLYryDZitmC2YTZhCDYp9mE2KzZiNiv2Kkg2YLZhNmK2YTYp9mL2Iwg2YTZg9mG2Ycg2YrZiNmB2LEg2YXYs9in2K3YqSDZh9in2KbZhNipISIKICAgICAgICApCiAgICAgICAgCiAgICAgICAgYXdhaXQgdXBkYXRlLm1lc3NhZ2UucmVwbHlfdGV4dChoZWxwX3RleHQsIHBhcnNlX21vZGU9J01hcmtkb3duJykKICAgIAogICAgYXN5bmMgZGVmIGhhbmRsZV91cmwoc2VsZiwgdXBkYXRlOiBVcGRhdGUsIGNvbnRleHQ6IENvbnRleHRUeXBlcy5ERUZBVUxUX1RZUEUpOgogICAgICAgICIiItmF2LnYp9mE2KzYqSDYsdin2KjYtyDYp9mE2YHZitiv2YrZiCIiIgogICAgICAgIHVybCA9IHVwZGF0ZS5tZXNzYWdlLnRleHQuc3RyaXAoKQogICAgICAgIAogICAgICAgICMg2KfZhNiq2K3ZgtmCINmF2YYg2KfZhNix2KfYqNi3CiAgICAgICAgaWYgbm90ICh1cmwuc3RhcnRzd2l0aCgnaHR0cDovLycpIG9yIHVybC5zdGFydHN3aXRoKCdodHRwczovLycpKToKICAgICAgICAgICAgYXdhaXQgdXBkYXRlLm1lc3NhZ2UucmVwbHlfdGV4dCgKICAgICAgICAgICAgICAgICLinYwgKirYsdin2KjYtyDYutmK2LEg2LXYrdmK2K0hKipcblxuIgogICAgICAgICAgICAgICAgItij2LHYs9mEINix2KfYqNi3INi12K3ZititINmK2KjYr9ijINio2YAgaHR0cDovLyDYo9mIIGh0dHBzOi8vIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIHJldHVybgogICAgICAgIAogICAgICAgICMg2LHYs9in2YTYqSDYp9mE2KjYr9in2YrYqQogICAgICAgIHN0YXR1c19tc2cgPSBhd2FpdCB1cGRhdGUubWVzc2FnZS5yZXBseV90ZXh0KAogICAgICAgICAgICAi4o+zICoq2KzYp9ix2Yog2KfZhNmF2LnYp9mE2KzYqS4uLioqXG5cbiIKICAgICAgICAgICAgIvCfk6Ug2KrYrdmF2YrZhCDYp9mE2YHZitiv2YrZiC4uLiIsCiAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICkKICAgICAgICAKICAgICAgICB0cnk6CiAgICAgICAgICAgICMgMS4g2KrYrdmF2YrZhCDYp9mE2YHZitiv2YrZiAogICAgICAgICAgICBhd2FpdCBzdGF0dXNfbXNnLmVkaXRfdGV4dCgKICAgICAgICAgICAgICAgICLij7MgKirYrNin2LHZiiDYp9mE2YXYudin2YTYrNipLi4uKipcblxuIgogICAgICAgICAgICAgICAgIvCfk6Ug2KrYrdmF2YrZhCDYp9mE2YHZitiv2YrZiC4uLiDij7HvuI8iLAogICAgICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgICAgICkKICAgICAgICAgICAgCiAgICAgICAgICAgIGlucHV0X3ZpZGVvID0gYXdhaXQgYXN5bmNpby50b190aHJlYWQoCiAgICAgICAgICAgICAgICBzZWxmLmNvbXByZXNzb3IuZG93bmxvYWRfdmlkZW8sCiAgICAgICAgICAgICAgICB1cmwKICAgICAgICAgICAgKQogICAgICAgICAgICAKICAgICAgICAgICAgIyAyLiDYtti62Lcg2KfZhNmB2YrYr9mK2YgKICAgICAgICAgICAgYXdhaXQgc3RhdHVzX21zZy5lZGl0X3RleHQoCiAgICAgICAgICAgICAgICAi4o+zICoq2KzYp9ix2Yog2KfZhNmF2LnYp9mE2KzYqS4uLioqXG5cbiIKICAgICAgICAgICAgICAgICLinIUg2KrZhSDYp9mE2KrYrdmF2YrZhCFcbiIKICAgICAgICAgICAgICAgICLwn5SlINis2KfYsdmKINin2YTYtti62Lcg2KfZhNmB2KfYptmCLi4uIOKPse+4j1xuXG4iCiAgICAgICAgICAgICAgICAi4pqg77iPINmC2K8g2YrYs9iq2LrYsdmCINi52K/YqSDYr9mC2KfYptmCLi4uIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICBsYXN0X3VwZGF0ZSA9IFswXSAgIyDZhNmE2KrYrdmD2YUg2YHZiiDZhdi52K/ZhCDYp9mE2KrYrdiv2YrYq9in2KoKICAgICAgICAgICAgCiAgICAgICAgICAgIGRlZiBwcm9ncmVzc191cGRhdGUocHJvZ3Jlc3MsIGN1cnJlbnQsIHRvdGFsKToKICAgICAgICAgICAgICAgICIiItiq2K3Yr9mK2Ksg2KfZhNiq2YLYr9mFIiIiCiAgICAgICAgICAgICAgICBjdXJyZW50X3RpbWUgPSB0aW1lLnRpbWUoKQogICAgICAgICAgICAgICAgaWYgY3VycmVudF90aW1lIC0gbGFzdF91cGRhdGVbMF0gPiA1OiAgIyDYqtit2K/ZitirINmD2YQgNSDYq9mI2KfZhtmNCiAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICBhc3luY2lvLmNyZWF0ZV90YXNrKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgc3RhdHVzX21zZy5lZGl0X3RleHQoCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZiLij7MgKirYrNin2LHZiiDYp9mE2LbYuti3INin2YTZgdin2KbZgi4uLioqXG5cbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIvCfk4og2KfZhNiq2YLYr9mFOiB7cHJvZ3Jlc3M6LjFmfSVcbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIuKPse+4jyB7aW50KGN1cnJlbnQvNjApfTp7aW50KGN1cnJlbnQlNjApOjAyZH0gLyB7aW50KHRvdGFsLzYwKX06e2ludCh0b3RhbCU2MCk6MDJkfSIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICAgICAgbGFzdF91cGRhdGVbMF0gPSBjdXJyZW50X3RpbWUKICAgICAgICAgICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgCiAgICAgICAgICAgIGNvbXByZXNzZWRfdmlkZW8sIGZpbGVfc2l6ZSA9IGF3YWl0IGFzeW5jaW8udG9fdGhyZWFkKAogICAgICAgICAgICAgICAgc2VsZi5jb21wcmVzc29yLnVsdHJhX2NvbXByZXNzLAogICAgICAgICAgICAgICAgaW5wdXRfdmlkZW8sCiAgICAgICAgICAgICAgICBwcm9ncmVzc191cGRhdGUKICAgICAgICAgICAgKQogICAgICAgICAgICAKICAgICAgICAgICAgIyAzLiDYqtmC2LPZitmFINil2LDYpyDZhNiy2YUg2KfZhNij2YXYsQogICAgICAgICAgICBhd2FpdCBzdGF0dXNfbXNnLmVkaXRfdGV4dCgKICAgICAgICAgICAgICAgICLij7MgKirYrNin2LHZiiDYp9mE2YXYudin2YTYrNipLi4uKipcblxuIgogICAgICAgICAgICAgICAgIuKchSDYqtmFINin2YTYtti62Lcg2KjZhtis2KfYrSFcbiIKICAgICAgICAgICAgICAgICLwn5OkINis2KfYsdmKINin2YTYqtit2LbZitixINmE2YTYpdix2LPYp9mELi4uIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICBwYXJ0cyA9IGF3YWl0IGFzeW5jaW8udG9fdGhyZWFkKAogICAgICAgICAgICAgICAgc2VsZi5jb21wcmVzc29yLnNwbGl0X3ZpZGVvX2lmX25lZWRlZCwKICAgICAgICAgICAgICAgIGNvbXByZXNzZWRfdmlkZW8KICAgICAgICAgICAgKQogICAgICAgICAgICAKICAgICAgICAgICAgIyA0LiDYsdmB2Lkg2KfZhNmB2YrYr9mK2Ygv2KfZhNij2KzYstin2KEKICAgICAgICAgICAgaWYgbGVuKHBhcnRzKSA9PSAxOgogICAgICAgICAgICAgICAgIyDZgdmK2K/ZitmIINmI2KfYrdivCiAgICAgICAgICAgICAgICBhd2FpdCBzdGF0dXNfbXNnLmVkaXRfdGV4dCgKICAgICAgICAgICAgICAgICAgICAi8J+TpCAqKtis2KfYsdmKINin2YTYpdix2LPYp9mELi4uKioiLAogICAgICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICB3aXRoIG9wZW4ocGFydHNbMF0sICdyYicpIGFzIHZpZGVvOgogICAgICAgICAgICAgICAgICAgIGF3YWl0IHVwZGF0ZS5tZXNzYWdlLnJlcGx5X3ZpZGVvKAogICAgICAgICAgICAgICAgICAgICAgICB2aWRlbz12aWRlbywKICAgICAgICAgICAgICAgICAgICAgICAgY2FwdGlvbj1mIuKchSAqKtiq2YUg2KfZhNi22LrYtyDYqNmG2KzYp9itISoqXG5cbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIvCfk6Yg2KfZhNit2KzZhToge2ZpbGVfc2l6ZTouMmZ9INmF2YrYrNin2KjYp9mK2KpcbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIvCflKUg2LbYuti3INmB2KfYptmCINin2YTZgtmI2KkhIiwKICAgICAgICAgICAgICAgICAgICAgICAgc3VwcG9ydHNfc3RyZWFtaW5nPVRydWUsCiAgICAgICAgICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgb3MucmVtb3ZlKHBhcnRzWzBdKQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgIyDYudiv2Kkg2KPYrNiy2KfYoQogICAgICAgICAgICAgICAgYXdhaXQgc3RhdHVzX21zZy5lZGl0X3RleHQoCiAgICAgICAgICAgICAgICAgICAgZiLwn5OmICoq2KrZhSDYp9mE2KrZgtiz2YrZhSDYpdmE2Ykge2xlbihwYXJ0cyl9INij2KzYstin2KEqKlxuXG4iCiAgICAgICAgICAgICAgICAgICAgZiLwn5OkINis2KfYsdmKINin2YTYpdix2LPYp9mELi4uIiwKICAgICAgICAgICAgICAgICAgICBwYXJzZV9tb2RlPSdNYXJrZG93bicKICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgZm9yIGksIHBhcnQgaW4gZW51bWVyYXRlKHBhcnRzLCAxKToKICAgICAgICAgICAgICAgICAgICBwYXJ0X3NpemUgPSBvcy5wYXRoLmdldHNpemUocGFydCkgLyAxMDI0IC8gMTAyNAogICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgIHdpdGggb3BlbihwYXJ0LCAncmInKSBhcyB2aWRlbzoKICAgICAgICAgICAgICAgICAgICAgICAgYXdhaXQgdXBkYXRlLm1lc3NhZ2UucmVwbHlfdmlkZW8oCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB2aWRlbz12aWRlbywKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNhcHRpb249ZiLwn5OmICoq2KfZhNis2LLYoSB7aX0ve2xlbihwYXJ0cyl9KipcbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZiLwn5OmINin2YTYrdis2YU6IHtwYXJ0X3NpemU6LjJmfSDZhdmK2KzYp9io2KfZitiqIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHN1cHBvcnRzX3N0cmVhbWluZz1UcnVlLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICBvcy5yZW1vdmUocGFydCkKICAgICAgICAgICAgCiAgICAgICAgICAgICMg2LHYs9in2YTYqSDYp9mE2YbYrNin2K0KICAgICAgICAgICAgYXdhaXQgc3RhdHVzX21zZy5lZGl0X3RleHQoCiAgICAgICAgICAgICAgICAi4pyFICoq2KrZhSDYqNmG2KzYp9itISoqXG5cbiIKICAgICAgICAgICAgICAgICLwn5SEINij2LHYs9mEINix2KfYqNi3INii2K7YsSDZhNmE2YXYstmK2K8hIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICAjINiq2YbYuNmK2YEg2KfZhNmF2YTZgdin2KoKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgb3MucmVtb3ZlKGlucHV0X3ZpZGVvKQogICAgICAgICAgICAgICAgaWYgb3MucGF0aC5leGlzdHMoY29tcHJlc3NlZF92aWRlbyk6CiAgICAgICAgICAgICAgICAgICAgb3MucmVtb3ZlKGNvbXByZXNzZWRfdmlkZW8pCiAgICAgICAgICAgIGV4Y2VwdDoKICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAKICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgICAgIGVycm9yX3RleHQgPSAoCiAgICAgICAgICAgICAgICBmIuKdjCAqKtit2K/YqyDYrti32KMhKipcblxuIgogICAgICAgICAgICAgICAgZiLwn5OdINin2YTYrti32KM6IGB7c3RyKGUpWzoyMDBdfWBcblxuIgogICAgICAgICAgICAgICAgZiLwn5KhICoq2K3ZhNmI2YQg2YXZgtiq2LHYrdipOioqXG4iCiAgICAgICAgICAgICAgICBmIuKAoiDYqtit2YLZgiDZhdmGINi12K3YqSDYp9mE2LHYp9io2LdcbiIKICAgICAgICAgICAgICAgIGYi4oCiINiq2KPZg9ivINij2YYg2KfZhNmF2YTZgSDYudin2YUgKEdvb2dsZSBEcml2ZSlcbiIKICAgICAgICAgICAgICAgIGYi4oCiINit2KfZiNmEINmF2LHYqSDYo9iu2LHZiSDZhNin2K3Zgtin2YtcblxuIgogICAgICAgICAgICAgICAgZiLwn4aYINmE2YTZhdiz2KfYudiv2Kk6IC9oZWxwIgogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICBhd2FpdCBzdGF0dXNfbXNnLmVkaXRfdGV4dChlcnJvcl90ZXh0LCBwYXJzZV9tb2RlPSdNYXJrZG93bicpCiAgICAgICAgICAgIGxvZ2dlci5lcnJvcihmIkVycm9yOiB7ZX0iKQogICAgCiAgICBkZWYgcnVuKHNlbGYpOgogICAgICAgICIiItiq2LTYutmK2YQg2KfZhNio2YjYqiIiIgogICAgICAgIHByaW50KCI9IiAqIDcwKQogICAgICAgIHByaW50KCLwn5SlINio2K/YoSDYqti02LrZitmEINio2YjYqiDYp9mE2LbYuti3INin2YTZgdin2KbZgiIpCiAgICAgICAgcHJpbnQoIj0iICogNzApCiAgICAgICAgcHJpbnQoZiLwn5OBINin2YTZhdis2YTYryDYp9mE2YXYpNmC2Ko6IHtURU1QX0RJUn0iKQogICAgICAgIHByaW50KGYi8J+OryDYpdi52K/Yp9iv2KfYqiDYp9mE2LbYuti3OiBDUkY9MzgsIDQ4MHAsIDIwZnBzLCBBdWRpbz0zMmsgbW9ubyIpCiAgICAgICAgcHJpbnQoZiLwn5OmINit2K8g2LHZgdi5IFRlbGVncmFtOiB7TUFYX1RFTEVHUkFNX1NJWkVfTUJ9INmF2YrYrNin2KjYp9mK2KoiKQogICAgICAgIHByaW50KCLinIUg2KfZhNio2YjYqiDYrNin2YfYsiDZhNmE2LnZhdmEISIpCiAgICAgICAgcHJpbnQoIj0iICogNzApCiAgICAgICAgCiAgICAgICAgIyDYqtmFINiq2LnYr9mK2YTZhyDZhNmE2LnZhdmEINmB2YogdGhyZWFkCgogICAgICAgIAogICAgICAgIGltcG9ydCBhc3luY2lvCgogICAgICAgIAogICAgICAgIGxvb3AgPSBhc3luY2lvLm5ld19ldmVudF9sb29wKCkKCiAgICAgICAgCiAgICAgICAgYXN5bmNpby5zZXRfZXZlbnRfbG9vcChsb29wKQoKICAgICAgICAKICAgICAgICBhc3luYyBkZWYgcnVuKCk6CgogICAgICAgIAogICAgICAgICAgICBhd2FpdCBzZWxmLmFwcC5pbml0aWFsaXplKCkKCiAgICAgICAgCiAgICAgICAgICAgIGF3YWl0IHNlbGYuYXBwLnN0YXJ0KCkKCiAgICAgICAgCiAgICAgICAgICAgIGF3YWl0IHNlbGYuYXBwLnVwZGF0ZXIuc3RhcnRfcG9sbGluZygpCgogICAgICAgIAogICAgICAgICAgICB0cnk6CgogICAgICAgIAogICAgICAgICAgICAgICAgd2hpbGUgVHJ1ZToKCiAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgYXdhaXQgYXN5bmNpby5zbGVlcCgxKQoKICAgICAgICAKICAgICAgICAgICAgZXhjZXB0OgoKICAgICAgICAKICAgICAgICAgICAgICAgIHBhc3MKCiAgICAgICAgCiAgICAgICAgICAgIGZpbmFsbHk6CgogICAgICAgIAogICAgICAgICAgICAgICAgYXdhaXQgc2VsZi5hcHAudXBkYXRlci5zdG9wKCkKCiAgICAgICAgCiAgICAgICAgICAgICAgICBhd2FpdCBzZWxmLmFwcC5zdG9wKCkKCiAgICAgICAgCiAgICAgICAgICAgICAgICBhd2FpdCBzZWxmLmFwcC5zaHV0ZG93bigpCgogICAgICAgIAogICAgICAgIGxvb3AucnVuX3VudGlsX2NvbXBsZXRlKHJ1bigpKQoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMg8J+OryDZhtmC2LfYqSDYp9mE2KjYr9in2YrYqQojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICB0cnk6CiAgICAgICAgIyDYp9mE2KrYrdmC2YIg2YXZhiBGRm1wZWcKICAgICAgICB0cnk6CiAgICAgICAgICAgIHN1YnByb2Nlc3MucnVuKFsnZmZtcGVnJywgJy12ZXJzaW9uJ10sIGNhcHR1cmVfb3V0cHV0PVRydWUsIGNoZWNrPVRydWUpCiAgICAgICAgICAgIHByaW50KCLinIUg2KrZhSDYp9mE2LnYq9mI2LEg2LnZhNmJIEZGbXBlZyIpCiAgICAgICAgZXhjZXB0IChzdWJwcm9jZXNzLkNhbGxlZFByb2Nlc3NFcnJvciwgRmlsZU5vdEZvdW5kRXJyb3IpOgogICAgICAgICAgICBwcmludCgi4p2MIEZGbXBlZyDYutmK2LEg2YXYq9io2KohIikKICAgICAgICAgICAgcHJpbnQoItin2YTYsdis2KfYoSDYqtir2KjZitiq2Ycg2KjYp9mE2KPZhdixOiBzdWRvIGFwdCBpbnN0YWxsIGZmbXBlZyIpCiAgICAgICAgICAgIGV4aXQoMSkKICAgICAgICAKICAgICAgICAjINin2YTYqtit2YLZgiDZhdmGINiq2YjZg9mGINin2YTYqNmI2KoKICAgICAgICBpZiBCT1RfVE9LRU4gPT0gIllPVVJfQk9UX1RPS0VOX0hFUkUiOgogICAgICAgICAgICBwcmludCgi4p2MINin2YTYsdis2KfYoSDYqti52K/ZitmEIEJPVF9UT0tFTiDZgdmKINin2YTZg9mI2K8hIikKICAgICAgICAgICAgZXhpdCgxKQogICAgICAgIAogICAgICAgICMg2KrYtNi62YrZhCDYp9mE2KjZiNiqCiAgICAgICAgYm90ID0gVWx0cmFDb21wcmVzc29yQm90KEJPVF9UT0tFTikKICAgICAgICBib3QucnVuKCkKICAgIAogICAgZXhjZXB0IEtleWJvYXJkSW50ZXJydXB0OgogICAgICAgIHByaW50KCJcbvCfkYsg2KrZhSDYpdmK2YLYp9mBINin2YTYqNmI2Kog2KjZiNin2LPYt9ipINin2YTZhdiz2KrYrtiv2YUiKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHByaW50KGYi4p2MINiu2LfYoyDZgdin2K/YrToge2V9IikKICAgICAgICBleGl0KDEpCg==",
}

# أسماء البوتات
BOTS_NAMES = {
    1: "2.py",
}

# تبعيات كل بوت
BOTS_IMPORTS = {
}

def load_helper_files(bot_num):
    """تحميل الملفات المساعدة التي يحتاجها البوت"""
    if bot_num not in BOTS_IMPORTS:
        return
    
    for module_name in BOTS_IMPORTS[bot_num]:
        if module_name in HELPER_FILES:
            try:
                # فك التشفير
                code = base64.b64decode(HELPER_FILES[module_name]).decode("utf-8")
                
                # إنشاء module
                module = types.ModuleType(module_name)
                
                # تنفيذ الكود
                exec(code, module.__dict__)
                
                # إضافة للنظام
                sys.modules[module_name] = module
                
                print(f"      ✓ تم تحميل {module_name}")
            except Exception as e:
                print(f"      ❌ خطأ في تحميل {module_name}: {e}")

def run_bot(bot_num):
    bot_name = BOTS_NAMES[bot_num]
    print(f"\n🤖 تشغيل: {bot_name}")
    bots_status[bot_num] = {"name": bot_name, "status": "starting"}
    try:
        # تحميل الملفات المساعدة
        load_helper_files(bot_num)
        
        # فك تشفير وتشغيل البوت
        code = base64.b64decode(BOTS_CODE[bot_num]).decode("utf-8")
        bots_status[bot_num]["status"] = "running"
        exec(code, {"__name__": "__main__"})
    except Exception as e:
        print(f"❌ خطأ في {bot_name}: {e}")
        bots_status[bot_num]["status"] = "error"
        bots_status[bot_num]["error"] = str(e)
        import traceback
        traceback.print_exc()

def main():
    global start_time
    start_time = datetime.now()
    
    print("=" * 70)
    print("🚀 تشغيل 1 بوت مع Flask")
    print("=" * 70)
    
    # تشغيل Flask
    print("\n🌐 تشغيل Flask Server...")
    threading.Thread(target=run_flask, daemon=True).start()
    time.sleep(2)
    print("✅ Flask يعمل")
    
    # تشغيل البوتات
    for bot_num in range(1, 2):
        threading.Thread(target=run_bot, args=(bot_num,), daemon=True).start()
        time.sleep(1.5)
    
    print("\n" + "=" * 70)
    print("✅ جميع البوتات تعمل!")
    print("🌐 Flask: http://0.0.0.0:" + str(os.environ.get("PORT", 8080)))
    print("=" * 70)
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n⛔ توقف")

if __name__ == "__main__":
    main()
