#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ملف مدمج - 1 بوت
تم الدمج تلقائياً من جميع ملفات .py
مع Flask - للاستضافات التي تسمح بـ Webserver
"""
import os, sys, threading, time, base64
import types
from flask import Flask, jsonify
from datetime import datetime

# Flask Application
app = Flask(__name__)

# متغير لحفظ حالة البوتات
bots_status = {}
start_time = None

@app.route("/")
def home():
    """الصفحة الرئيسية - تعرض حالة جميع البوتات"""
    global start_time
    uptime = str(datetime.now() - start_time).split(".")[0] if start_time else "0"
    
    html = """
    <!DOCTYPE html>
    <html dir="rtl" lang="ar">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>🤖 نظام إدارة البوتات</title>
        <style>
            * {{
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }}
            body {{
                font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
                padding: 20px;
            }}
            .container {{
                background: white;
                border-radius: 20px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                padding: 40px;
                max-width: 600px;
                width: 100%;
            }}
            h1 {{
                color: #667eea;
                text-align: center;
                margin-bottom: 10px;
                font-size: 2em;
            }}
            .uptime {{
                text-align: center;
                color: #666;
                margin-bottom: 30px;
                font-size: 0.9em;
            }}
            .status {{
                background: #f8f9fa;
                border-radius: 15px;
                padding: 25px;
            }}
            .status h2 {{
                color: #10b981;
                text-align: center;
                margin-bottom: 20px;
            }}
            .bot-item {{
                background: white;
                border-radius: 10px;
                padding: 15px;
                margin-bottom: 10px;
                display: flex;
                align-items: center;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }}
            .bot-icon {{
                font-size: 2em;
                margin-left: 15px;
            }}
            .bot-info {{
                flex: 1;
            }}
            .bot-name {{
                font-weight: bold;
                color: #333;
                font-size: 1.1em;
            }}
            .bot-status {{
                color: #10b981;
                font-size: 0.9em;
                margin-top: 5px;
            }}
            .footer {{
                text-align: center;
                margin-top: 30px;
                color: #666;
                font-size: 0.9em;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🤖 نظام إدارة البوتات</h1>
            <div class="uptime">⏱️ وقت التشغيل: {uptime}</div>
            
            <div class="status">
                <h2>✅ جميع البوتات تعمل (1 بوت)</h2>
                <div class="bot-item">
                    <div class="bot-icon">🤖</div>
                    <div class="bot-info">
                        <div class="bot-name">2.py</div>
                        <div class="bot-status">✓ يعمل بشكل طبيعي</div>
                    </div>
                </div>
            </div>
            
            <div class="footer">
                Made with ❤️ | Powered by Flask + Telegram Bot
            </div>
        </div>
    </body>
    </html>
    """
    return html

@app.route("/status")
def status():
    """API endpoint - يعرض حالة البوتات بصيغة JSON"""
    return jsonify({
        "total_bots": 1,
        "status": "running",
        "bots": bots_status,
        "uptime": str(datetime.now() - start_time) if start_time else "0"
    })

@app.route("/health")
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy"}), 200

def run_flask():
    """تشغيل Flask server"""
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)

# أكواد البوتات
BOTS_CODE = {
    1: "IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIK8J+OrCDYttin2LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiAtINmF2K3Ys9mR2YYg2YTZgCBSZW5kZXIgRnJlZSBUaWVyCtmK2KrYudin2YXZhCDZhdi5INmC2YrZiNivIFJlbmRlciAoMTUg2K/ZgtmK2YLYqSB0aW1lb3V0LCA1MTIgTUIgUkFNKQoK2KfZhNmF2YXZitiy2KfYqjoK4pyFINit2K8g2KPZgti12Ykg2YTZhdiv2Kkg2KfZhNmB2YrYr9mK2YggKDMwINiv2YLZitmC2KkpCuKchSDYrdivINij2YLYtdmJINmE2K3YrNmFINin2YTZgdmK2K/ZitmIICgzMDAgTUIpCuKchSDYqtmG2LjZitmBINiq2YTZgtin2KbZiiDZhNmE2LDYp9mD2LHYqQrinIUg2YXYudin2YTYrNipIGFzeW5jINit2YLZitmC2YrYqQrinIUgdGltZW91dCBwcm90ZWN0aW9uCuKchSDYrtmK2KfYsdin2Kog2LbYuti3INmF2K3Ys9mR2YbYqQoiIiIKCmltcG9ydCBvcwppbXBvcnQgYXN5bmNpbwppbXBvcnQgcmVxdWVzdHMKaW1wb3J0IHN1YnByb2Nlc3MKaW1wb3J0IHJlCmltcG9ydCB0aW1lCmltcG9ydCBsb2dnaW5nCmltcG9ydCBqc29uCmltcG9ydCBnYwppbXBvcnQgcHN1dGlsCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aApmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZQpmcm9tIHRlbGVncmFtIGltcG9ydCBVcGRhdGUsIElubGluZUtleWJvYXJkQnV0dG9uLCBJbmxpbmVLZXlib2FyZE1hcmt1cApmcm9tIHRlbGVncmFtLmV4dCBpbXBvcnQgQXBwbGljYXRpb24sIENvbW1hbmRIYW5kbGVyLCBNZXNzYWdlSGFuZGxlciwgQ2FsbGJhY2tRdWVyeUhhbmRsZXIsIENvbnRleHRUeXBlcywgZmlsdGVycwoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMg4pqZ77iPINil2LnYr9in2K/Yp9iqIFJlbmRlciDYp9mE2YXYrdiz2ZHZhtipCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKQk9UX1RPS0VOID0gIjg1MDQ2NDg1NTA6QUFHSDRUbzR2UnQ3M0YwZU9ISEJSM0JzRDlJU2EtMHpBdEkiClRFTVBfRElSID0gIi4vdGVtcF92aWRlb3MiCk1BWF9WSURFT19EVVJBVElPTl9NSU5VVEVTID0gMzAgICMg2K3YryDYo9mC2LXZiTogMzAg2K/ZgtmK2YLYqQpNQVhfVklERU9fU0laRV9NQiA9IDEwMDAgICMg2K3YryDYo9mC2LXZiTogMzAwINmF2YrYrNin2KjYp9mK2KoKTUFYX1RFTEVHUkFNX1NJWkVfTUIgPSA1MCAgIyDYrdivIFRlbGVncmFtClBST0NFU1NJTkdfVElNRU9VVF9TRUNPTkRTID0gNjAwICAjIDEwINiv2YLYp9im2YIgbWF4INmE2YTYtti62LcKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojIPCfk50g2KfZhNiq2LPYrNmK2YQKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cgpsb2dnaW5nLmJhc2ljQ29uZmlnKAogICAgZm9ybWF0PSclKGFzY3RpbWUpcyAtICUobmFtZSlzIC0gJShsZXZlbG5hbWUpcyAtICUobWVzc2FnZSlzJywKICAgIGxldmVsPWxvZ2dpbmcuSU5GTwopCmxvZ2dlciA9IGxvZ2dpbmcuZ2V0TG9nZ2VyKF9fbmFtZV9fKQoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMg8J+OrCDZhdit2LHZgyDYp9mE2LbYuti3INin2YTZhdit2LPZkdmGCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKY2xhc3MgU21hcnRDb21wcmVzc29yOgogICAgIiIi2YXYrdix2YMg2LbYuti3INiw2YPZiiDZhdi5INit2YXYp9mK2Kkg2YXZhiB0aW1lb3V0IiIiCiAgICAKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB0ZW1wX2Rpcj1URU1QX0RJUik6CiAgICAgICAgc2VsZi50ZW1wX2RpciA9IFBhdGgodGVtcF9kaXIpCiAgICAgICAgc2VsZi50ZW1wX2Rpci5ta2RpcihleGlzdF9vaz1UcnVlKQogICAgCiAgICBkZWYgY2xlYW51cF9tZW1vcnkoc2VsZik6CiAgICAgICAgIiIi2KrZhti42YrZgSDYp9mE2LDYp9mD2LHYqSIiIgogICAgICAgIGdjLmNvbGxlY3QoKQogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+SviDYp9mE2LDYp9mD2LHYqSDYp9mE2YXYs9iq2K7Yr9mF2Kk6IHtwc3V0aWwuUHJvY2VzcygpLm1lbW9yeV9pbmZvKCkucnNzIC8gMTAyNCAvIDEwMjQ6LjFmfSBNQiIpCiAgICAKICAgIGRlZiBleHRyYWN0X2dvb2dsZV9kcml2ZV9pZChzZWxmLCB1cmwpOgogICAgICAgICIiItin2LPYqtiu2LHYp9isINmF2LnYsdmBIEdvb2dsZSBEcml2ZSIiIgogICAgICAgIHBhdHRlcm5zID0gWwogICAgICAgICAgICByJ2lkPShbYS16QS1aMC05Xy1dKyknLAogICAgICAgICAgICByJy9kLyhbYS16QS1aMC05Xy1dKyknLAogICAgICAgICAgICByJ29wZW5cP2lkPShbYS16QS1aMC05Xy1dKyknLAogICAgICAgIF0KICAgICAgICAKICAgICAgICBmb3IgcGF0dGVybiBpbiBwYXR0ZXJuczoKICAgICAgICAgICAgbWF0Y2ggPSByZS5zZWFyY2gocGF0dGVybiwgdXJsKQogICAgICAgICAgICBpZiBtYXRjaDoKICAgICAgICAgICAgICAgIHJldHVybiBtYXRjaC5ncm91cCgxKQogICAgICAgIHJldHVybiBOb25lCiAgICAKICAgIGFzeW5jIGRlZiBkb3dubG9hZF92aWRlbyhzZWxmLCB1cmwsIG1heF9zaXplX21iPU1BWF9WSURFT19TSVpFX01CKToKICAgICAgICAiIiLYqtit2YXZitmEINmB2YrYr9mK2Ygg2YXYuSDYrdivINij2YLYtdmJINmE2YTYrdis2YUiIiIKICAgICAgICBsb2dnZXIuaW5mbyhmIvCfk6Ug2KjYr9ihINin2YTYqtit2YXZitmEINmF2YY6IHt1cmxbOjEwMF19Li4uIikKICAgICAgICAKICAgICAgICBvdXRwdXRfcGF0aCA9IHNlbGYudGVtcF9kaXIgLyAiaW5wdXRfdmlkZW8ubXA0IgogICAgICAgIAogICAgICAgIGZpbGVfaWQgPSBzZWxmLmV4dHJhY3RfZ29vZ2xlX2RyaXZlX2lkKHVybCkKICAgICAgICAKICAgICAgICBpZiBmaWxlX2lkOgogICAgICAgICAgICBsb2dnZXIuaW5mbyhmIvCflI0gR29vZ2xlIERyaXZlIGRldGVjdGVkIikKICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgaW1wb3J0IGdkb3duCiAgICAgICAgICAgICAgICBkb3dubG9hZF91cmwgPSBmImh0dHBzOi8vZHJpdmUuZ29vZ2xlLmNvbS91Yz9pZD17ZmlsZV9pZH0iCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICMg2KrYrdmF2YrZhCDZhdi5INmF2LHYp9mC2KjYqSDYp9mE2K3YrNmFCiAgICAgICAgICAgICAgICBkZWYgcHJvZ3Jlc3NfY2FsbGJhY2soY3VycmVudCwgdG90YWwpOgogICAgICAgICAgICAgICAgICAgIGlmIHRvdGFsIGFuZCAodG90YWwgLyAxMDI0IC8gMTAyNCkgPiBtYXhfc2l6ZV9tYjoKICAgICAgICAgICAgICAgICAgICAgICAgcmFpc2UgRXhjZXB0aW9uKGYi2KfZhNmF2YTZgSDZg9io2YrYsSDYrNiv2KfZiyEg2KfZhNit2K8g2KfZhNij2YLYtdmJIHttYXhfc2l6ZV9tYn0g2YXZitis2KfYqNin2YrYqiIpCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIGdkb3duLmRvd25sb2FkKGRvd25sb2FkX3VybCwgc3RyKG91dHB1dF9wYXRoKSwgcXVpZXQ9RmFsc2UpCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgZXhjZXB0IEltcG9ydEVycm9yOgogICAgICAgICAgICAgICAgIyDYt9ix2YrZgtipINio2K/ZitmE2KkKICAgICAgICAgICAgICAgIGRvd25sb2FkX3VybCA9IGYiaHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL3VjP2lkPXtmaWxlX2lkfSZleHBvcnQ9ZG93bmxvYWQmY29uZmlybT10IgogICAgICAgICAgICAgICAgcmVzcG9uc2UgPSByZXF1ZXN0cy5nZXQoZG93bmxvYWRfdXJsLCBzdHJlYW09VHJ1ZSwgdGltZW91dD0xMjApCiAgICAgICAgICAgICAgICByZXNwb25zZS5yYWlzZV9mb3Jfc3RhdHVzKCkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgdG90YWxfc2l6ZSA9IGludChyZXNwb25zZS5oZWFkZXJzLmdldCgnY29udGVudC1sZW5ndGgnLCAwKSkKICAgICAgICAgICAgICAgIGlmIHRvdGFsX3NpemUgPiBtYXhfc2l6ZV9tYiAqIDEwMjQgKiAxMDI0OgogICAgICAgICAgICAgICAgICAgIHJhaXNlIEV4Y2VwdGlvbihmItin2YTZhdmE2YEg2YPYqNmK2LEg2KzYr9in2YshICh7dG90YWxfc2l6ZS8xMDI0LzEwMjQ6LjBmfSBNQikgLSDYp9mE2K3YryDYp9mE2KPZgti12Ykge21heF9zaXplX21ifSBNQiIpCiAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgIHdpdGggb3BlbihvdXRwdXRfcGF0aCwgJ3diJykgYXMgZjoKICAgICAgICAgICAgICAgICAgICBmb3IgY2h1bmsgaW4gcmVzcG9uc2UuaXRlcl9jb250ZW50KGNodW5rX3NpemU9NjU1MzYpOgogICAgICAgICAgICAgICAgICAgICAgICBpZiBjaHVuazoKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYud3JpdGUoY2h1bmspCiAgICAgICAgZWxzZToKICAgICAgICAgICAgIyDYqtit2YXZitmEINmF2KjYp9i02LEKICAgICAgICAgICAgcmVzcG9uc2UgPSByZXF1ZXN0cy5nZXQodXJsLCBzdHJlYW09VHJ1ZSwgdGltZW91dD0xMjApCiAgICAgICAgICAgIHJlc3BvbnNlLnJhaXNlX2Zvcl9zdGF0dXMoKQogICAgICAgICAgICAKICAgICAgICAgICAgdG90YWxfc2l6ZSA9IGludChyZXNwb25zZS5oZWFkZXJzLmdldCgnY29udGVudC1sZW5ndGgnLCAwKSkKICAgICAgICAgICAgaWYgdG90YWxfc2l6ZSA+IG1heF9zaXplX21iICogMTAyNCAqIDEwMjQ6CiAgICAgICAgICAgICAgICByYWlzZSBFeGNlcHRpb24oZiLYp9mE2YXZhNmBINmD2KjZitixINis2K/Yp9mLISAoe3RvdGFsX3NpemUvMTAyNC8xMDI0Oi4wZn0gTUIpIC0g2KfZhNit2K8g2KfZhNij2YLYtdmJIHttYXhfc2l6ZV9tYn0gTUIiKQogICAgICAgICAgICAKICAgICAgICAgICAgd2l0aCBvcGVuKG91dHB1dF9wYXRoLCAnd2InKSBhcyBmOgogICAgICAgICAgICAgICAgZm9yIGNodW5rIGluIHJlc3BvbnNlLml0ZXJfY29udGVudChjaHVua19zaXplPTY1NTM2KToKICAgICAgICAgICAgICAgICAgICBpZiBjaHVuazoKICAgICAgICAgICAgICAgICAgICAgICAgZi53cml0ZShjaHVuaykKICAgICAgICAKICAgICAgICBmaWxlX3NpemUgPSBvcy5wYXRoLmdldHNpemUob3V0cHV0X3BhdGgpIC8gMTAyNCAvIDEwMjQKICAgICAgICBsb2dnZXIuaW5mbyhmIuKchSDYqtmFINin2YTYqtit2YXZitmEOiB7ZmlsZV9zaXplOi4yZn0gTUIiKQogICAgICAgIAogICAgICAgICMg2KrZhti42YrZgSDYp9mE2LDYp9mD2LHYqQogICAgICAgIHNlbGYuY2xlYW51cF9tZW1vcnkoKQogICAgICAgIAogICAgICAgIHJldHVybiBzdHIob3V0cHV0X3BhdGgpLCBmaWxlX3NpemUKICAgIAogICAgYXN5bmMgZGVmIGdldF92aWRlb19pbmZvKHNlbGYsIHZpZGVvX3BhdGgpOgogICAgICAgICIiItin2YTYrdi12YjZhCDYudmE2Ykg2YXYudmE2YjZhdin2Kog2KfZhNmB2YrYr9mK2YgiIiIKICAgICAgICBjbWQgPSBbCiAgICAgICAgICAgICdmZnByb2JlJywKICAgICAgICAgICAgJy12JywgJ3F1aWV0JywKICAgICAgICAgICAgJy1wcmludF9mb3JtYXQnLCAnanNvbicsCiAgICAgICAgICAgICctc2hvd19mb3JtYXQnLAogICAgICAgICAgICBzdHIodmlkZW9fcGF0aCkKICAgICAgICBdCiAgICAgICAgCiAgICAgICAgcmVzdWx0ID0gc3VicHJvY2Vzcy5ydW4oY21kLCBjYXB0dXJlX291dHB1dD1UcnVlLCB0ZXh0PVRydWUpCiAgICAgICAgaW5mbyA9IGpzb24ubG9hZHMocmVzdWx0LnN0ZG91dCkKICAgICAgICAKICAgICAgICBkdXJhdGlvbiA9IGZsb2F0KGluZm9bJ2Zvcm1hdCddWydkdXJhdGlvbiddKQogICAgICAgIHJldHVybiBkdXJhdGlvbgogICAgCiAgICBhc3luYyBkZWYgY29tcHJlc3NfdmlkZW8oc2VsZiwgaW5wdXRfcGF0aCwgcXVhbGl0eT0nbWF4aW11bV9jb21wcmVzc2lvbicsIHByb2dyZXNzX2NhbGxiYWNrPU5vbmUpOgogICAgICAgICIiIgogICAgICAgINi22LrYtyDZgdmK2K/ZitmIINmF2LkgdGltZW91dCBwcm90ZWN0aW9uCiAgICAgICAgIiIiCiAgICAgICAgbG9nZ2VyLmluZm8oZiLwn5SlINio2K/YoSDYp9mE2LbYuti3Li4uIikKICAgICAgICAKICAgICAgICAjINin2YTYrdi12YjZhCDYudmE2Ykg2YXYr9ipINin2YTZgdmK2K/ZitmICiAgICAgICAgZHVyYXRpb24gPSBhd2FpdCBzZWxmLmdldF92aWRlb19pbmZvKGlucHV0X3BhdGgpCiAgICAgICAgZHVyYXRpb25fbWludXRlcyA9IGR1cmF0aW9uIC8gNjAKICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKPse+4jyDZhdiv2Kkg2KfZhNmB2YrYr9mK2Yg6IHtkdXJhdGlvbl9taW51dGVzOi4xZn0g2K/ZgtmK2YLYqSIpCiAgICAgICAgCiAgICAgICAgIyDYsdmB2LYg2KfZhNmB2YrYr9mK2YjZh9in2Kog2KfZhNi32YjZitmE2Kkg2KzYr9in2YsKICAgICAgICBpZiBkdXJhdGlvbl9taW51dGVzID4gTUFYX1ZJREVPX0RVUkFUSU9OX01JTlVURVM6CiAgICAgICAgICAgIHJhaXNlIEV4Y2VwdGlvbigKICAgICAgICAgICAgICAgIGYi4pqg77iPINin2YTZgdmK2K/ZitmIINi32YjZitmEINis2K/Yp9mLISAoe2R1cmF0aW9uX21pbnV0ZXM6LjBmfSDYr9mC2YrZgtipKVxuIgogICAgICAgICAgICAgICAgZiLYp9mE2K3YryDYp9mE2KPZgti12Yk6IHtNQVhfVklERU9fRFVSQVRJT05fTUlOVVRFU30g2K/ZgtmK2YLYqVxuXG4iCiAgICAgICAgICAgICAgICBmIvCfkqEg2KzYsdioINmB2YrYr9mK2Ygg2KPZgti12LEg2YTZhNit2LXZiNmEINi52YTZiSDZhtiq2KfYptisINij2YHYttmEIgogICAgICAgICAgICApCiAgICAgICAgCiAgICAgICAgb3V0cHV0X3BhdGggPSBzZWxmLnRlbXBfZGlyIC8gImNvbXByZXNzZWQubXA0IgogICAgICAgIAogICAgICAgICMg2KXYudiv2KfYr9in2Kog2KfZhNi22LrYtyDYp9mE2YXYrdiz2ZHZhtipINmE2YAgUmVuZGVyCiAgICAgICAgcXVhbGl0eV9zZXR0aW5ncyA9IHsKICAgICAgICAgICAgJ21heGltdW1fY29tcHJlc3Npb24nOiB7CiAgICAgICAgICAgICAgICAnY3JmJzogJzQwJywKICAgICAgICAgICAgICAgICdwcmVzZXQnOiAndWx0cmFmYXN0JywgICMg2KPYs9ix2Lkg2YXYpyDZitmF2YPZhgogICAgICAgICAgICAgICAgJ3NjYWxlJzogJzQ4MDotMicsCiAgICAgICAgICAgICAgICAnZnBzJzogJzE4JywKICAgICAgICAgICAgICAgICdhdWRpb19iaXRyYXRlJzogJzI0aycsCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgICdiYWxhbmNlZCc6IHsKICAgICAgICAgICAgICAgICdjcmYnOiAnMzUnLAogICAgICAgICAgICAgICAgJ3ByZXNldCc6ICd2ZXJ5ZmFzdCcsCiAgICAgICAgICAgICAgICAnc2NhbGUnOiAnNjQwOi0yJywKICAgICAgICAgICAgICAgICdmcHMnOiAnMjQnLAogICAgICAgICAgICAgICAgJ2F1ZGlvX2JpdHJhdGUnOiAnMzJrJywKICAgICAgICAgICAgfSwKICAgICAgICB9CiAgICAgICAgCiAgICAgICAgc2V0dGluZ3MgPSBxdWFsaXR5X3NldHRpbmdzLmdldChxdWFsaXR5LCBxdWFsaXR5X3NldHRpbmdzWydtYXhpbXVtX2NvbXByZXNzaW9uJ10pCiAgICAgICAgCiAgICAgICAgIyDYo9mF2LEgRkZtcGVnCiAgICAgICAgY21kID0gWwogICAgICAgICAgICAnZmZtcGVnJywKICAgICAgICAgICAgJy1pJywgc3RyKGlucHV0X3BhdGgpLAogICAgICAgICAgICAnLWM6dicsICdsaWJ4MjY0JywKICAgICAgICAgICAgJy1wcmVzZXQnLCBzZXR0aW5nc1sncHJlc2V0J10sCiAgICAgICAgICAgICctY3JmJywgc2V0dGluZ3NbJ2NyZiddLAogICAgICAgICAgICAnLXZmJywgZiJzY2FsZT17c2V0dGluZ3NbJ3NjYWxlJ119LGZwcz17c2V0dGluZ3NbJ2ZwcyddfSIsCiAgICAgICAgICAgICctYzphJywgJ2FhYycsCiAgICAgICAgICAgICctYjphJywgc2V0dGluZ3NbJ2F1ZGlvX2JpdHJhdGUnXSwKICAgICAgICAgICAgJy1hYycsICcxJywKICAgICAgICAgICAgJy1tb3ZmbGFncycsICcrZmFzdHN0YXJ0JywKICAgICAgICAgICAgJy15JywKICAgICAgICAgICAgc3RyKG91dHB1dF9wYXRoKQogICAgICAgIF0KICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKame+4jyDYqNiv2KEg2KfZhNi22LrYtyAodGltZW91dDoge1BST0NFU1NJTkdfVElNRU9VVF9TRUNPTkRTfXMpLi4uIikKICAgICAgICAKICAgICAgICAjINiq2LTYutmK2YQgRkZtcGVnINmF2LkgdGltZW91dAogICAgICAgIHByb2Nlc3MgPSBzdWJwcm9jZXNzLlBvcGVuKAogICAgICAgICAgICBjbWQsCiAgICAgICAgICAgIHN0ZG91dD1zdWJwcm9jZXNzLlBJUEUsCiAgICAgICAgICAgIHN0ZGVycj1zdWJwcm9jZXNzLlBJUEUsCiAgICAgICAgICAgIHVuaXZlcnNhbF9uZXdsaW5lcz1UcnVlCiAgICAgICAgKQogICAgICAgIAogICAgICAgIHN0YXJ0X3RpbWUgPSB0aW1lLnRpbWUoKQogICAgICAgIGxhc3RfcHJvZ3Jlc3MgPSAwCiAgICAgICAgCiAgICAgICAgdHJ5OgogICAgICAgICAgICAjINmF2LHYp9mC2KjYqSDYp9mE2KrZgtiv2YUg2YXYuSB0aW1lb3V0CiAgICAgICAgICAgIGZvciBsaW5lIGluIHByb2Nlc3Muc3RkZXJyOgogICAgICAgICAgICAgICAgIyDZgdit2LUgdGltZW91dAogICAgICAgICAgICAgICAgaWYgdGltZS50aW1lKCkgLSBzdGFydF90aW1lID4gUFJPQ0VTU0lOR19USU1FT1VUX1NFQ09ORFM6CiAgICAgICAgICAgICAgICAgICAgcHJvY2Vzcy5raWxsKCkKICAgICAgICAgICAgICAgICAgICByYWlzZSBUaW1lb3V0RXJyb3IoCiAgICAgICAgICAgICAgICAgICAgICAgIGYi4o+x77iPINin2YTYtti62Lcg2KfYs9iq2LrYsdmCINmI2YLYqtin2Ysg2LfZiNmK2YTYp9mLISAo2KPZg9ir2LEg2YXZhiB7UFJPQ0VTU0lOR19USU1FT1VUX1NFQ09ORFMvNjA6LjBmfSDYr9mC2YrZgtipKVxuIgogICAgICAgICAgICAgICAgICAgICAgICBmItis2LHYqCDZgdmK2K/ZitmIINij2YLYtdixINij2Ygg2KfYqti12YQg2KjYp9mE2K/YudmFIgogICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgaWYgJ3RpbWU9JyBpbiBsaW5lOgogICAgICAgICAgICAgICAgICAgIG1hdGNoID0gcmUuc2VhcmNoKHIndGltZT0oXGQrKTooXGQrKTooXGQrKScsIGxpbmUpCiAgICAgICAgICAgICAgICAgICAgaWYgbWF0Y2g6CiAgICAgICAgICAgICAgICAgICAgICAgIGgsIG0sIHMgPSBtYXAoaW50LCBtYXRjaC5ncm91cHMoKSkKICAgICAgICAgICAgICAgICAgICAgICAgY3VycmVudF90aW1lID0gaCAqIDM2MDAgKyBtICogNjAgKyBzCiAgICAgICAgICAgICAgICAgICAgICAgIHByb2dyZXNzID0gKGN1cnJlbnRfdGltZSAvIGR1cmF0aW9uKSAqIDEwMCBpZiBkdXJhdGlvbiA+IDAgZWxzZSAwCiAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAjINiq2K3Yr9mK2Ksg2YPZhCAxMCUKICAgICAgICAgICAgICAgICAgICAgICAgaWYgcHJvZ3Jlc3MgLSBsYXN0X3Byb2dyZXNzID49IDEwOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgbG9nZ2VyLmluZm8oZiLwn46sINin2YTYqtmC2K/ZhToge3Byb2dyZXNzOi4wZn0lIikKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGlmIHByb2dyZXNzX2NhbGxiYWNrOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGF3YWl0IHByb2dyZXNzX2NhbGxiYWNrKHByb2dyZXNzKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgbGFzdF9wcm9ncmVzcyA9IHByb2dyZXNzCiAgICAgICAgICAgIAogICAgICAgICAgICBwcm9jZXNzLndhaXQodGltZW91dD0xMCkKICAgICAgICAgICAgCiAgICAgICAgICAgIGlmIHByb2Nlc3MucmV0dXJuY29kZSAhPSAwOgogICAgICAgICAgICAgICAgcmFpc2UgRXhjZXB0aW9uKCLZgdi02YQg2KfZhNi22LrYtyEiKQogICAgICAgICAgICAKICAgICAgICBleGNlcHQgc3VicHJvY2Vzcy5UaW1lb3V0RXhwaXJlZDoKICAgICAgICAgICAgcHJvY2Vzcy5raWxsKCkKICAgICAgICAgICAgcmFpc2UgVGltZW91dEVycm9yKCLYp9mE2LbYuti3INin2LPYqti62LHZgiDZiNmC2KrYp9mLINi32YjZitmE2KfZiyDYrNiv2KfZiyEiKQogICAgICAgIAogICAgICAgICMg2K3Ys9in2Kgg2KfZhNmG2KrYp9im2KwKICAgICAgICBvcmlnaW5hbF9zaXplID0gb3MucGF0aC5nZXRzaXplKGlucHV0X3BhdGgpIC8gMTAyNCAvIDEwMjQKICAgICAgICBjb21wcmVzc2VkX3NpemUgPSBvcy5wYXRoLmdldHNpemUob3V0cHV0X3BhdGgpIC8gMTAyNCAvIDEwMjQKICAgICAgICBjb21wcmVzc2lvbl9yYXRpbyA9ICgxIC0gY29tcHJlc3NlZF9zaXplIC8gb3JpZ2luYWxfc2l6ZSkgKiAxMDAKICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKchSDYp9mD2KrZhdmEINin2YTYtti62LchIikKICAgICAgICBsb2dnZXIuaW5mbyhmIvCfk4og2KfZhNit2KzZhSDYp9mE2KPYtdmE2Yo6IHtvcmlnaW5hbF9zaXplOi4yZn0gTUIiKQogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+TpiDYp9mE2K3YrNmFINin2YTZhdi22LrZiNi3OiB7Y29tcHJlc3NlZF9zaXplOi4yZn0gTUIiKQogICAgICAgIGxvZ2dlci5pbmZvKGYi8J+OryDYp9mE2KrZiNmB2YrYsToge2NvbXByZXNzaW9uX3JhdGlvOi4xZn0lIikKICAgICAgICAKICAgICAgICAjINiq2YbYuNmK2YEKICAgICAgICBzZWxmLmNsZWFudXBfbWVtb3J5KCkKICAgICAgICAKICAgICAgICByZXR1cm4gc3RyKG91dHB1dF9wYXRoKSwgY29tcHJlc3NlZF9zaXplCiAgICAKICAgIGFzeW5jIGRlZiBzcGxpdF9pZl9uZWVkZWQoc2VsZiwgdmlkZW9fcGF0aCwgbWF4X3NpemVfbWI9TUFYX1RFTEVHUkFNX1NJWkVfTUIpOgogICAgICAgICIiItiq2YLYs9mK2YUg2KXYsNinINmE2LLZhSDYp9mE2KPZhdixIiIiCiAgICAgICAgZmlsZV9zaXplID0gb3MucGF0aC5nZXRzaXplKHZpZGVvX3BhdGgpIC8gMTAyNCAvIDEwMjQKICAgICAgICAKICAgICAgICBpZiBmaWxlX3NpemUgPD0gbWF4X3NpemVfbWI6CiAgICAgICAgICAgIHJldHVybiBbdmlkZW9fcGF0aF0KICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKcgu+4jyDYp9mE2KrZgtiz2YrZhSDYpdmE2Ykg2KPYrNiy2KfYoS4uLiIpCiAgICAgICAgCiAgICAgICAgZHVyYXRpb24gPSBhd2FpdCBzZWxmLmdldF92aWRlb19pbmZvKHZpZGVvX3BhdGgpCiAgICAgICAgbnVtX3BhcnRzID0gaW50KGZpbGVfc2l6ZSAvIG1heF9zaXplX21iKSArIDEKICAgICAgICBwYXJ0X2R1cmF0aW9uID0gZHVyYXRpb24gLyBudW1fcGFydHMKICAgICAgICAKICAgICAgICBwYXJ0cyA9IFtdCiAgICAgICAgCiAgICAgICAgZm9yIGkgaW4gcmFuZ2UobnVtX3BhcnRzKToKICAgICAgICAgICAgc3RhcnRfdGltZSA9IGkgKiBwYXJ0X2R1cmF0aW9uCiAgICAgICAgICAgIHBhcnRfcGF0aCA9IHNlbGYudGVtcF9kaXIgLyBmInBhcnRfe2krMTowMmR9Lm1wNCIKICAgICAgICAgICAgCiAgICAgICAgICAgIGNtZCA9IFsKICAgICAgICAgICAgICAgICdmZm1wZWcnLAogICAgICAgICAgICAgICAgJy1pJywgc3RyKHZpZGVvX3BhdGgpLAogICAgICAgICAgICAgICAgJy1zcycsIHN0cihzdGFydF90aW1lKSwKICAgICAgICAgICAgICAgICctdCcsIHN0cihwYXJ0X2R1cmF0aW9uKSwKICAgICAgICAgICAgICAgICctYycsICdjb3B5JywKICAgICAgICAgICAgICAgICcteScsCiAgICAgICAgICAgICAgICBzdHIocGFydF9wYXRoKQogICAgICAgICAgICBdCiAgICAgICAgICAgIAogICAgICAgICAgICBzdWJwcm9jZXNzLnJ1bihjbWQsIGNhcHR1cmVfb3V0cHV0PVRydWUsIGNoZWNrPVRydWUpCiAgICAgICAgICAgIHBhcnRzLmFwcGVuZChzdHIocGFydF9wYXRoKSkKICAgICAgICAKICAgICAgICBsb2dnZXIuaW5mbyhmIuKchSDYqtmFINin2YTYqtmC2LPZitmFINil2YTZiSB7bGVuKHBhcnRzKX0g2KPYrNiy2KfYoSIpCiAgICAgICAgcmV0dXJuIHBhcnRzCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyDwn6SWINin2YTYqNmI2KoKIyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpjbGFzcyBPcHRpbWl6ZWRCb3Q6CiAgICAiIiLYqNmI2Kog2YXYrdiz2ZHZhiDZhNmAIFJlbmRlciIiIgogICAgCiAgICBkZWYgX19pbml0X18oc2VsZiwgdG9rZW4pOgogICAgICAgIHNlbGYudG9rZW4gPSB0b2tlbgogICAgICAgIHNlbGYuYXBwID0gQXBwbGljYXRpb24uYnVpbGRlcigpLnRva2VuKHRva2VuKS5idWlsZCgpCiAgICAgICAgc2VsZi5jb21wcmVzc29yID0gU21hcnRDb21wcmVzc29yKCkKICAgICAgICAKICAgICAgICAjINin2YTZhdi52KfZhNis2KfYqgogICAgICAgIHNlbGYuYXBwLmFkZF9oYW5kbGVyKENvbW1hbmRIYW5kbGVyKCJzdGFydCIsIHNlbGYuc3RhcnRfY29tbWFuZCkpCiAgICAgICAgc2VsZi5hcHAuYWRkX2hhbmRsZXIoQ29tbWFuZEhhbmRsZXIoImhlbHAiLCBzZWxmLmhlbHBfY29tbWFuZCkpCiAgICAgICAgc2VsZi5hcHAuYWRkX2hhbmRsZXIoTWVzc2FnZUhhbmRsZXIoZmlsdGVycy5URVhUICYgfmZpbHRlcnMuQ09NTUFORCwgc2VsZi5oYW5kbGVfdXJsKSkKICAgICAgICBzZWxmLmFwcC5hZGRfaGFuZGxlcihDYWxsYmFja1F1ZXJ5SGFuZGxlcihzZWxmLmhhbmRsZV9xdWFsaXR5KSkKICAgIAogICAgYXN5bmMgZGVmIHN0YXJ0X2NvbW1hbmQoc2VsZiwgdXBkYXRlOiBVcGRhdGUsIGNvbnRleHQ6IENvbnRleHRUeXBlcy5ERUZBVUxUX1RZUEUpOgogICAgICAgICIiItin2YTYqNiv2KfZitipIiIiCiAgICAgICAgYXdhaXQgdXBkYXRlLm1lc3NhZ2UucmVwbHlfdGV4dCgKICAgICAgICAgICAgIvCfjqwgKirYttin2LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiAtINmF2K3Ys9mR2YYg2YTZgCBSZW5kZXIqKlxuXG4iCiAgICAgICAgICAgICLwn5SlICoq2LbYuti3INmC2YjZiiDZhNmE2YHZitiv2YrZiNmH2KfYqiEqKlxuXG4iCiAgICAgICAgICAgICLimqDvuI8gKirYp9mE2YLZitmI2K86KipcbiIKICAgICAgICAgICAgZiLigKIg2KfZhNit2K8g2KfZhNij2YLYtdmJINmE2YTZhdiv2Kk6IHtNQVhfVklERU9fRFVSQVRJT05fTUlOVVRFU30g2K/ZgtmK2YLYqVxuIgogICAgICAgICAgICBmIuKAoiDYp9mE2K3YryDYp9mE2KPZgti12Ykg2YTZhNit2KzZhToge01BWF9WSURFT19TSVpFX01CfSDZhdmK2KzYp9io2KfZitiqXG5cbiIKICAgICAgICAgICAgIvCfk4sgKirZg9mK2YEg2KrYs9iq2K7Yr9mF2YbZijoqKlxuIgogICAgICAgICAgICAiMe+4j+KDoyDYo9ix2LPZhCDYsdin2KjYtyDYp9mE2YHZitiv2YrZiFxuIgogICAgICAgICAgICAiMu+4j+KDoyDYp9iu2KrYsSDZhdiz2KrZiNmJINin2YTYtti62LdcbiIKICAgICAgICAgICAgIjPvuI/ig6Mg2KfYrdi12YQg2LnZhNmJINin2YTZgdmK2K/ZitmIINin2YTZhdi22LrZiNi3IVxuXG4iCiAgICAgICAgICAgICLwn4aYINmE2YTZhdiz2KfYudiv2Kk6IC9oZWxwIiwKICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgKQogICAgCiAgICBhc3luYyBkZWYgaGVscF9jb21tYW5kKHNlbGYsIHVwZGF0ZTogVXBkYXRlLCBjb250ZXh0OiBDb250ZXh0VHlwZXMuREVGQVVMVF9UWVBFKToKICAgICAgICAiIiLYp9mE2YXYs9in2LnYr9ipIiIiCiAgICAgICAgYXdhaXQgdXBkYXRlLm1lc3NhZ2UucmVwbHlfdGV4dCgKICAgICAgICAgICAgIvCfk5ogKirYr9mE2YrZhCDYp9mE2KfYs9iq2K7Yr9in2YU6KipcblxuIgogICAgICAgICAgICAiKirYp9mE2LHZiNin2KjYtyDYp9mE2YXYr9i52YjZhdipOioqXG4iCiAgICAgICAgICAgICLigKIgR29vZ2xlIERyaXZlXG4iCiAgICAgICAgICAgICLigKIg2LHZiNin2KjYtyDZhdio2KfYtNix2KkgKC5tcDQpXG5cbiIKICAgICAgICAgICAgZiIqKtin2YTZgtmK2YjYryAoUmVuZGVyIEZyZWUpOioqXG4iCiAgICAgICAgICAgIGYi4oCiINin2YTZhdiv2Kk6INit2KrZiSB7TUFYX1ZJREVPX0RVUkFUSU9OX01JTlVURVN9INiv2YLZitmC2KlcbiIKICAgICAgICAgICAgZiLigKIg2KfZhNit2KzZhTog2K3YqtmJIHtNQVhfVklERU9fU0laRV9NQn0g2YXZitis2KfYqNin2YrYqlxuIgogICAgICAgICAgICBmIuKAoiDZiNmC2Kog2KfZhNmF2LnYp9mE2KzYqToge1BST0NFU1NJTkdfVElNRU9VVF9TRUNPTkRTLzYwOi4wZn0g2K/ZgtmK2YLYqVxuXG4iCiAgICAgICAgICAgICIqKtmG2LXYp9im2K06KipcbiIKICAgICAgICAgICAgIuKAoiDYp9iz2KrYrtiv2YUgJ9i22LrYtyDYo9mC2LXZiScg2YTYo9i12LrYsSDYrdis2YVcbiIKICAgICAgICAgICAgIuKAoiDYp9mE2YHZitiv2YrZiNmH2KfYqiDYp9mE2YLYtdmK2LHYqSDYo9iz2LHYuVxuIgogICAgICAgICAgICAi4oCiINiq2KzZhtioINin2YTZgdmK2K/ZitmI2YfYp9iqIDRLIiwKICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgKQogICAgCiAgICBhc3luYyBkZWYgaGFuZGxlX3VybChzZWxmLCB1cGRhdGU6IFVwZGF0ZSwgY29udGV4dDogQ29udGV4dFR5cGVzLkRFRkFVTFRfVFlQRSk6CiAgICAgICAgIiIi2YXYudin2YTYrNipINin2YTYsdin2KjYtyIiIgogICAgICAgIHVybCA9IHVwZGF0ZS5tZXNzYWdlLnRleHQuc3RyaXAoKQogICAgICAgIAogICAgICAgIGlmIG5vdCAodXJsLnN0YXJ0c3dpdGgoJ2h0dHA6Ly8nKSBvciB1cmwuc3RhcnRzd2l0aCgnaHR0cHM6Ly8nKSk6CiAgICAgICAgICAgIGF3YWl0IHVwZGF0ZS5tZXNzYWdlLnJlcGx5X3RleHQoCiAgICAgICAgICAgICAgICAi4p2MINix2KfYqNi3INi62YrYsSDYtdit2YrYrSEiLAogICAgICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgICAgICkKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgCiAgICAgICAgY29udGV4dC51c2VyX2RhdGFbJ3ZpZGVvX3VybCddID0gdXJsCiAgICAgICAgCiAgICAgICAgIyDYrtmK2KfYsdin2Kog2KfZhNi22LrYtwogICAgICAgIGtleWJvYXJkID0gWwogICAgICAgICAgICBbSW5saW5lS2V5Ym9hcmRCdXR0b24oIvCflKUg2LbYuti3INij2YLYtdmJICjYo9i12LrYsSDYrdis2YUpIiwgY2FsbGJhY2tfZGF0YT0ncXVhbGl0eV9tYXhpbXVtJyldLAogICAgICAgICAgICBbSW5saW5lS2V5Ym9hcmRCdXR0b24oIuKalu+4jyDZhdiq2YjYp9iy2YYgKNis2YjYr9ipINij2YHYttmEKSIsIGNhbGxiYWNrX2RhdGE9J3F1YWxpdHlfYmFsYW5jZWQnKV0sCiAgICAgICAgXQogICAgICAgIHJlcGx5X21hcmt1cCA9IElubGluZUtleWJvYXJkTWFya3VwKGtleWJvYXJkKQogICAgICAgIAogICAgICAgIGF3YWl0IHVwZGF0ZS5tZXNzYWdlLnJlcGx5X3RleHQoCiAgICAgICAgICAgICLwn46vICoq2KfYrtiq2LEg2YXYs9iq2YjZiSDYp9mE2LbYuti3OioqXG5cbiIKICAgICAgICAgICAgIvCflKUgKirYtti62Lcg2KPZgti12YkqKjog2KPYtdi62LEg2K3YrNmFICg0ODBwLCAxOGZwcykgLSDYqtmI2YHZitixIDkwJStcbiIKICAgICAgICAgICAgIuKalu+4jyAqKtmF2KrZiNin2LLZhioqOiDYrNmI2K/YqSDYo9mB2LbZhCAoNjQwcCwgMjRmcHMpIC0g2KrZiNmB2YrYsSA4NSVcblxuIgogICAgICAgICAgICAi8J+SoSDZhNmE2YHZitiv2YrZiNmH2KfYqiDYp9mE2LfZiNmK2YTYqTog2KfYrtiq2LEg2LbYuti3INij2YLYtdmJIiwKICAgICAgICAgICAgcmVwbHlfbWFya3VwPXJlcGx5X21hcmt1cCwKICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgKQogICAgCiAgICBhc3luYyBkZWYgaGFuZGxlX3F1YWxpdHkoc2VsZiwgdXBkYXRlOiBVcGRhdGUsIGNvbnRleHQ6IENvbnRleHRUeXBlcy5ERUZBVUxUX1RZUEUpOgogICAgICAgICIiItmF2LnYp9mE2KzYqSDYp9iu2KrZitin2LEg2KfZhNis2YjYr9ipIiIiCiAgICAgICAgcXVlcnkgPSB1cGRhdGUuY2FsbGJhY2tfcXVlcnkKICAgICAgICBhd2FpdCBxdWVyeS5hbnN3ZXIoKQogICAgICAgIAogICAgICAgIHF1YWxpdHlfbWFwID0gewogICAgICAgICAgICAncXVhbGl0eV9tYXhpbXVtJzogKCdtYXhpbXVtX2NvbXByZXNzaW9uJywgJ/CflKUg2LbYuti3INij2YLYtdmJJyksCiAgICAgICAgICAgICdxdWFsaXR5X2JhbGFuY2VkJzogKCdiYWxhbmNlZCcsICfimpbvuI8g2YXYqtmI2KfYstmGJyksCiAgICAgICAgfQogICAgICAgIAogICAgICAgIHF1YWxpdHksIHF1YWxpdHlfbmFtZSA9IHF1YWxpdHlfbWFwLmdldChxdWVyeS5kYXRhLCAoJ21heGltdW1fY29tcHJlc3Npb24nLCAn8J+UpSDYtti62Lcg2KPZgti12YknKSkKICAgICAgICB1cmwgPSBjb250ZXh0LnVzZXJfZGF0YS5nZXQoJ3ZpZGVvX3VybCcpCiAgICAgICAgCiAgICAgICAgaWYgbm90IHVybDoKICAgICAgICAgICAgYXdhaXQgcXVlcnkuZWRpdF9tZXNzYWdlX3RleHQoIuKdjCDYrti32KM6INmE2YUg2YrYqtmFINin2YTYudir2YjYsSDYudmE2Ykg2KfZhNix2KfYqNi3IikKICAgICAgICAgICAgcmV0dXJuCiAgICAgICAgCiAgICAgICAgYXdhaXQgcXVlcnkuZWRpdF9tZXNzYWdlX3RleHQoCiAgICAgICAgICAgIGYi4o+zICoq2KzYp9ix2Yog2KfZhNmF2LnYp9mE2KzYqS4uLioqXG5cbiIKICAgICAgICAgICAgZiLwn5SXINin2YTYsdin2KjYtzogYHt1cmxbOjUwXX0uLi5gXG4iCiAgICAgICAgICAgIGYi8J+TiiDYp9mE2KzZiNiv2Kk6IHtxdWFsaXR5X25hbWV9XG5cbiIKICAgICAgICAgICAgZiLij7HvuI8g2KfZhNix2KzYp9ihINin2YTYp9mG2KrYuNin2LEuLi4iLAogICAgICAgICAgICBwYXJzZV9tb2RlPSdNYXJrZG93bicKICAgICAgICApCiAgICAgICAgCiAgICAgICAgdHJ5OgogICAgICAgICAgICAjIDEuINin2YTYqtit2YXZitmECiAgICAgICAgICAgIGF3YWl0IHF1ZXJ5LmVkaXRfbWVzc2FnZV90ZXh0KAogICAgICAgICAgICAgICAgIuKPsyAqKtis2KfYsdmKINin2YTYqtit2YXZitmELi4uKipcblxuIgogICAgICAgICAgICAgICAgIvCfk6Ug2KrYrdmF2YrZhCDYp9mE2YHZitiv2YrZiC4uLiIsCiAgICAgICAgICAgICAgICBwYXJzZV9tb2RlPSdNYXJrZG93bicKICAgICAgICAgICAgKQogICAgICAgICAgICAKICAgICAgICAgICAgaW5wdXRfdmlkZW8sIG9yaWdpbmFsX3NpemUgPSBhd2FpdCBzZWxmLmNvbXByZXNzb3IuZG93bmxvYWRfdmlkZW8odXJsKQogICAgICAgICAgICAKICAgICAgICAgICAgIyAyLiDYp9mE2LbYuti3CiAgICAgICAgICAgIGF3YWl0IHF1ZXJ5LmVkaXRfbWVzc2FnZV90ZXh0KAogICAgICAgICAgICAgICAgZiLij7MgKirYrNin2LHZiiDYp9mE2LbYuti3Li4uKipcblxuIgogICAgICAgICAgICAgICAgZiLwn5OKINin2YTYrdis2YUg2KfZhNij2LXZhNmKOiB7b3JpZ2luYWxfc2l6ZTouMmZ9IE1CXG4iCiAgICAgICAgICAgICAgICBmIvCflKUg2KfZhNis2YjYr9ipOiB7cXVhbGl0eV9uYW1lfVxuXG4iCiAgICAgICAgICAgICAgICBmIuKPse+4jyDZgtivINmK2LPYqti62LHZgiB7UFJPQ0VTU0lOR19USU1FT1VUX1NFQ09ORFMvNjA6LjBmfSDYr9mC2YrZgtipLi4uIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICBhc3luYyBkZWYgcHJvZ3Jlc3NfdXBkYXRlKHByb2dyZXNzKToKICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICBhd2FpdCBxdWVyeS5lZGl0X21lc3NhZ2VfdGV4dCgKICAgICAgICAgICAgICAgICAgICAgICAgZiLij7MgKirYrNin2LHZiiDYp9mE2LbYuti3Li4uKipcblxuIgogICAgICAgICAgICAgICAgICAgICAgICBmIvCfk4og2KfZhNiq2YLYr9mFOiB7cHJvZ3Jlc3M6LjBmfSVcbiIKICAgICAgICAgICAgICAgICAgICAgICAgZiLij7HvuI8g2KfZhNix2KzYp9ihINin2YTYp9mG2KrYuNin2LEuLi4iLAogICAgICAgICAgICAgICAgICAgICAgICBwYXJzZV9tb2RlPSdNYXJrZG93bicKICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBleGNlcHQ6CiAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICAKICAgICAgICAgICAgY29tcHJlc3NlZF92aWRlbywgY29tcHJlc3NlZF9zaXplID0gYXdhaXQgc2VsZi5jb21wcmVzc29yLmNvbXByZXNzX3ZpZGVvKAogICAgICAgICAgICAgICAgaW5wdXRfdmlkZW8sCiAgICAgICAgICAgICAgICBxdWFsaXR5LAogICAgICAgICAgICAgICAgcHJvZ3Jlc3NfdXBkYXRlCiAgICAgICAgICAgICkKICAgICAgICAgICAgCiAgICAgICAgICAgICMgMy4g2KfZhNiq2YLYs9mK2YUKICAgICAgICAgICAgcGFydHMgPSBhd2FpdCBzZWxmLmNvbXByZXNzb3Iuc3BsaXRfaWZfbmVlZGVkKGNvbXByZXNzZWRfdmlkZW8pCiAgICAgICAgICAgIAogICAgICAgICAgICAjIDQuINin2YTYpdix2LPYp9mECiAgICAgICAgICAgIGF3YWl0IHF1ZXJ5LmVkaXRfbWVzc2FnZV90ZXh0KAogICAgICAgICAgICAgICAgIvCfk6QgKirYrNin2LHZiiDYp9mE2KXYsdiz2KfZhC4uLioqIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgICAgIAogICAgICAgICAgICBpZiBsZW4ocGFydHMpID09IDE6CiAgICAgICAgICAgICAgICB3aXRoIG9wZW4ocGFydHNbMF0sICdyYicpIGFzIHZpZGVvOgogICAgICAgICAgICAgICAgICAgIGF3YWl0IHF1ZXJ5Lm1lc3NhZ2UucmVwbHlfdmlkZW8oCiAgICAgICAgICAgICAgICAgICAgICAgIHZpZGVvPXZpZGVvLAogICAgICAgICAgICAgICAgICAgICAgICBjYXB0aW9uPWYi4pyFICoq2KrZhSDYqNmG2KzYp9itISoqXG5cbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIvCfk6Yg2KfZhNit2KzZhToge2NvbXByZXNzZWRfc2l6ZTouMmZ9IE1CXG4iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZiLwn46vINin2YTYqtmI2YHZitixOiB7KDEgLSBjb21wcmVzc2VkX3NpemUvb3JpZ2luYWxfc2l6ZSkqMTAwOi4wZn0lIiwKICAgICAgICAgICAgICAgICAgICAgICAgc3VwcG9ydHNfc3RyZWFtaW5nPVRydWUsCiAgICAgICAgICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIG9zLnJlbW92ZShwYXJ0c1swXSkKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIGZvciBpLCBwYXJ0IGluIGVudW1lcmF0ZShwYXJ0cywgMSk6CiAgICAgICAgICAgICAgICAgICAgcGFydF9zaXplID0gb3MucGF0aC5nZXRzaXplKHBhcnQpIC8gMTAyNCAvIDEwMjQKICAgICAgICAgICAgICAgICAgICB3aXRoIG9wZW4ocGFydCwgJ3JiJykgYXMgdmlkZW86CiAgICAgICAgICAgICAgICAgICAgICAgIGF3YWl0IHF1ZXJ5Lm1lc3NhZ2UucmVwbHlfdmlkZW8oCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB2aWRlbz12aWRlbywKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNhcHRpb249ZiLwn5OmICoq2KfZhNis2LLYoSB7aX0ve2xlbihwYXJ0cyl9KipcbntwYXJ0X3NpemU6LjJmfSBNQiIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBzdXBwb3J0c19zdHJlYW1pbmc9VHJ1ZSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgb3MucmVtb3ZlKHBhcnQpCiAgICAgICAgICAgIAogICAgICAgICAgICBhd2FpdCBxdWVyeS5lZGl0X21lc3NhZ2VfdGV4dCgKICAgICAgICAgICAgICAgIGYi4pyFICoq2KrZhSDYqNmG2KzYp9itISoqXG5cbiIKICAgICAgICAgICAgICAgIGYi8J+OryDYp9mE2KrZiNmB2YrYsTogeygxIC0gY29tcHJlc3NlZF9zaXplL29yaWdpbmFsX3NpemUpKjEwMDouMGZ9JVxuIgogICAgICAgICAgICAgICAgZiLwn5SEINij2LHYs9mEINix2KfYqNi3INii2K7YsSEiLAogICAgICAgICAgICAgICAgcGFyc2VfbW9kZT0nTWFya2Rvd24nCiAgICAgICAgICAgICkKICAgICAgICAgICAgCiAgICAgICAgICAgICMg2KrZhti42YrZgQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBvcy5yZW1vdmUoaW5wdXRfdmlkZW8pCiAgICAgICAgICAgICAgICBpZiBvcy5wYXRoLmV4aXN0cyhjb21wcmVzc2VkX3ZpZGVvKToKICAgICAgICAgICAgICAgICAgICBvcy5yZW1vdmUoY29tcHJlc3NlZF92aWRlbykKICAgICAgICAgICAgZXhjZXB0OgogICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICAKICAgICAgICAgICAgc2VsZi5jb21wcmVzc29yLmNsZWFudXBfbWVtb3J5KCkKICAgICAgICAKICAgICAgICBleGNlcHQgVGltZW91dEVycm9yIGFzIGU6CiAgICAgICAgICAgIGF3YWl0IHF1ZXJ5LmVkaXRfbWVzc2FnZV90ZXh0KAogICAgICAgICAgICAgICAgZiLij7HvuI8gKirYp9mG2KrZh9iqINin2YTZhdmH2YTYqSEqKlxuXG4iCiAgICAgICAgICAgICAgICBmIvCfk50ge3N0cihlKX1cblxuIgogICAgICAgICAgICAgICAgZiLwn5KhINis2LHYqCDZgdmK2K/ZitmIINij2YLYtdixIiwKICAgICAgICAgICAgICAgIHBhcnNlX21vZGU9J01hcmtkb3duJwogICAgICAgICAgICApCiAgICAgICAgCiAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgICAgICBlcnJvcl9tc2cgPSBzdHIoZSkKICAgICAgICAgICAgYXdhaXQgcXVlcnkuZWRpdF9tZXNzYWdlX3RleHQoCiAgICAgICAgICAgICAgICBmIuKdjCAqKtiu2LfYoyEqKlxuXG4iCiAgICAgICAgICAgICAgICBmIvCfk50ge2Vycm9yX21zZ1s6MjAwXX1cblxuIgogICAgICAgICAgICAgICAgZiLwn5KhINiq2KPZg9ivINmF2YY6XG4iCiAgICAgICAgICAgICAgICBmIuKAoiDYp9mE2LHYp9io2Lcg2LXYrdmK2K1cbiIKICAgICAgICAgICAgICAgIGYi4oCiINin2YTZhdmE2YEg2LnYp9mFIChHb29nbGUgRHJpdmUpXG4iCiAgICAgICAgICAgICAgICBmIuKAoiDYp9mE2YXYr9ipIDwge01BWF9WSURFT19EVVJBVElPTl9NSU5VVEVTfSDYr9mC2YrZgtipXG4iCiAgICAgICAgICAgICAgICBmIuKAoiDYp9mE2K3YrNmFIDwge01BWF9WSURFT19TSVpFX01CfSBNQiIsCiAgICAgICAgICAgICAgICBwYXJzZV9tb2RlPSdNYXJrZG93bicKICAgICAgICAgICAgKQogICAgCiAgICBkZWYgcnVuKHNlbGYpOgogICAgICAgICIiItiq2LTYutmK2YQg2KfZhNio2YjYqiIiIgogICAgICAgIHByaW50KCI9IiAqIDcwKQogICAgICAgIHByaW50KCLwn5SlINio2YjYqiDYttin2LrYtyDYp9mE2YHZitiv2YrZiNmH2KfYqiAtINmF2K3Ys9mR2YYg2YTZgCBSZW5kZXIiKQogICAgICAgIHByaW50KCI9IiAqIDcwKQogICAgICAgIHByaW50KGYi8J+TgSDYp9mE2YXYrNmE2K8g2KfZhNmF2KTZgtiqOiB7VEVNUF9ESVJ9IikKICAgICAgICBwcmludChmIuKPse+4jyDYrdivINin2YTZhdiv2Kk6IHtNQVhfVklERU9fRFVSQVRJT05fTUlOVVRFU30g2K/ZgtmK2YLYqSIpCiAgICAgICAgcHJpbnQoZiLwn5OmINit2K8g2KfZhNit2KzZhToge01BWF9WSURFT19TSVpFX01CfSDZhdmK2KzYp9io2KfZitiqIikKICAgICAgICBwcmludChmIuKPsyBUaW1lb3V0OiB7UFJPQ0VTU0lOR19USU1FT1VUX1NFQ09ORFMvNjA6LjBmfSDYr9mC2YrZgtipIikKICAgICAgICBwcmludCgi4pyFINin2YTYqNmI2Kog2KzYp9mH2LIhIikKICAgICAgICBwcmludCgiPSIgKiA3MCkKICAgICAgICAKICAgICAgICAjINiq2YUg2KrYudiv2YrZhNmHINmE2YTYudmF2YQg2YHZiiB0aHJlYWQKCiAgICAgICAgCiAgICAgICAgaW1wb3J0IGFzeW5jaW8KCiAgICAgICAgCiAgICAgICAgbG9vcCA9IGFzeW5jaW8ubmV3X2V2ZW50X2xvb3AoKQoKICAgICAgICAKICAgICAgICBhc3luY2lvLnNldF9ldmVudF9sb29wKGxvb3ApCgogICAgICAgIAogICAgICAgIGFzeW5jIGRlZiBydW4oKToKCiAgICAgICAgCiAgICAgICAgICAgIGF3YWl0IHNlbGYuYXBwLmluaXRpYWxpemUoKQoKICAgICAgICAKICAgICAgICAgICAgYXdhaXQgc2VsZi5hcHAuc3RhcnQoKQoKICAgICAgICAKICAgICAgICAgICAgYXdhaXQgc2VsZi5hcHAudXBkYXRlci5zdGFydF9wb2xsaW5nKCkKCiAgICAgICAgCiAgICAgICAgICAgIHRyeToKCiAgICAgICAgCiAgICAgICAgICAgICAgICB3aGlsZSBUcnVlOgoKICAgICAgICAKICAgICAgICAgICAgICAgICAgICBhd2FpdCBhc3luY2lvLnNsZWVwKDEpCgogICAgICAgIAogICAgICAgICAgICBleGNlcHQ6CgogICAgICAgIAogICAgICAgICAgICAgICAgcGFzcwoKICAgICAgICAKICAgICAgICAgICAgZmluYWxseToKCiAgICAgICAgCiAgICAgICAgICAgICAgICBhd2FpdCBzZWxmLmFwcC51cGRhdGVyLnN0b3AoKQoKICAgICAgICAKICAgICAgICAgICAgICAgIGF3YWl0IHNlbGYuYXBwLnN0b3AoKQoKICAgICAgICAKICAgICAgICAgICAgICAgIGF3YWl0IHNlbGYuYXBwLnNodXRkb3duKCkKCiAgICAgICAgCiAgICAgICAgbG9vcC5ydW5fdW50aWxfY29tcGxldGUocnVuKCkpCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyDwn46vINin2YTYqNiv2KfZitipCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHRyeToKICAgICAgICBzdWJwcm9jZXNzLnJ1bihbJ2ZmbXBlZycsICctdmVyc2lvbiddLCBjYXB0dXJlX291dHB1dD1UcnVlLCBjaGVjaz1UcnVlKQogICAgICAgIHByaW50KCLinIUgRkZtcGVnINis2KfZh9iyIikKICAgIGV4Y2VwdDoKICAgICAgICBwcmludCgi4p2MIEZGbXBlZyDYutmK2LEg2YXYq9io2KohIikKICAgICAgICBleGl0KDEpCiAgICAKICAgIGJvdCA9IE9wdGltaXplZEJvdChCT1RfVE9LRU4pCiAgICBib3QucnVuKCkK",
}

# أسماء البوتات
BOTS_NAMES = {
    1: "2.py",
}

# تبعيات كل بوت
BOTS_IMPORTS = {
}

def load_helper_files(bot_num):
    """تحميل الملفات المساعدة التي يحتاجها البوت"""
    if bot_num not in BOTS_IMPORTS:
        return
    
    for module_name in BOTS_IMPORTS[bot_num]:
        if module_name in HELPER_FILES:
            try:
                # فك التشفير
                code = base64.b64decode(HELPER_FILES[module_name]).decode("utf-8")
                
                # إنشاء module
                module = types.ModuleType(module_name)
                
                # تنفيذ الكود
                exec(code, module.__dict__)
                
                # إضافة للنظام
                sys.modules[module_name] = module
                
                print(f"      ✓ تم تحميل {module_name}")
            except Exception as e:
                print(f"      ❌ خطأ في تحميل {module_name}: {e}")

def run_bot(bot_num):
    bot_name = BOTS_NAMES[bot_num]
    print(f"\n🤖 تشغيل: {bot_name}")
    bots_status[bot_num] = {"name": bot_name, "status": "starting"}
    try:
        # تحميل الملفات المساعدة
        load_helper_files(bot_num)
        
        # فك تشفير وتشغيل البوت
        code = base64.b64decode(BOTS_CODE[bot_num]).decode("utf-8")
        bots_status[bot_num]["status"] = "running"
        exec(code, {"__name__": "__main__"})
    except Exception as e:
        print(f"❌ خطأ في {bot_name}: {e}")
        bots_status[bot_num]["status"] = "error"
        bots_status[bot_num]["error"] = str(e)
        import traceback
        traceback.print_exc()

def main():
    global start_time
    start_time = datetime.now()
    
    print("=" * 70)
    print("🚀 تشغيل 1 بوت مع Flask")
    print("=" * 70)
    
    # تشغيل Flask
    print("\n🌐 تشغيل Flask Server...")
    threading.Thread(target=run_flask, daemon=True).start()
    time.sleep(2)
    print("✅ Flask يعمل")
    
    # تشغيل البوتات
    for bot_num in range(1, 2):
        threading.Thread(target=run_bot, args=(bot_num,), daemon=True).start()
        time.sleep(1.5)
    
    print("\n" + "=" * 70)
    print("✅ جميع البوتات تعمل!")
    print("🌐 Flask: http://0.0.0.0:" + str(os.environ.get("PORT", 8080)))
    print("=" * 70)
    
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n⛔ توقف")

if __name__ == "__main__":
    main()
